/**
 * Builds a well-formatted HTML string for PDF export via expo-print.
 * - Sections don't break across pages (page-break-inside: avoid)
 * - Compact spacing, balanced margins
 * - ALL-CAPS lines treated as section headers (bold, slightly larger)
 */
export function buildReportHtml(params: {
  title: string;       // e.g. "Training Program"
  subject: string;     // e.g. player name or team name
  date: string;        // formatted date string
  body: string;        // raw report text
}): string {
  const { title, subject, date, body } = params;
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const lines = body.split('\n');
  let html = '';
  let inSection = false;

  for (const raw of lines) {
    // Strip markdown syntax
    const clean = raw
      .replace(/#{1,6}\s*/g, '')
      .replace(/\*\*/g, '')
      .replace(/^-{3,}$|^={3,}$|^—{3,}$/, '')
      .trimEnd();

    const trimmed = clean.trim();

    if (!trimmed) {
      // Blank line — close section if open, small spacer
      if (inSection) {
        html += '</div>';
        inSection = false;
      }
      continue;
    }

    // Detect ALL-CAPS section header (short line, mostly uppercase)
    const isHeader =
      /^[A-Z][A-Z\s\/&()\d\-:]{2,}$/.test(trimmed) && trimmed.length < 70;

    if (isHeader) {
      if (inSection) { html += '</div>'; inSection = false; }
      html += `
        <div style="page-break-inside:avoid;margin-top:18px">
          <h3 style="font-size:12px;font-weight:800;color:#111;text-transform:uppercase;
                     letter-spacing:0.5px;margin:0 0 6px;border-bottom:1.5px solid #ddd;
                     padding-bottom:4px">${esc(trimmed)}</h3>`;
      inSection = true;
    } else if (/^[-•*]\s/.test(trimmed)) {
      // Bullet point
      const text = trimmed.replace(/^[-•*]\s/, '');
      html += `<p style="font-size:11px;line-height:1.6;color:#333;margin:2px 0 2px 12px">
                 • ${esc(text)}</p>`;
    } else {
      // Normal paragraph
      html += `<p style="font-size:11px;line-height:1.6;color:#333;margin:3px 0">${esc(trimmed)}</p>`;
    }
  }

  if (inSection) html += '</div>';

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
  @page { margin: 18mm 16mm; }
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #111;
         font-size: 11px; line-height: 1.5; }
  .cover { margin-bottom: 20px; border-bottom: 2px solid #111; padding-bottom: 10px; }
  .cover h1 { font-size: 18px; font-weight: 900; margin: 0 0 4px; }
  .cover .meta { font-size: 11px; color: #555; }
  .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center;
            font-size: 9px; color: #aaa; padding: 6px 0;
            border-top: 1px solid #eee; }
</style>
</head>
<body>
  <div class="cover">
    <h1>${esc(title)}</h1>
    <div class="meta">${esc(subject)} &nbsp;·&nbsp; ${esc(date)}</div>
  </div>
  ${html}
  <div class="footer">Generated by BloomPrint · ${esc(date)}</div>
</body>
</html>`;
}

/** Returns a well-formatted file name: "ReportType - Subject - YYYY-MM-DD" */
export function buildPdfFileName(reportType: string, subject: string, date?: Date): string {
  const d = date ?? new Date();
  const dateStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  const safe = (s: string) => s.replace(/[^a-zA-Z0-9 \-]/g, '').replace(/\s+/g, ' ').trim();
  return `${safe(reportType)} - ${safe(subject)} - ${dateStr}`;
}
