import React, { useEffect, useState } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, StyleSheet, ActivityIndicator, Alert,
} from 'react-native';
import { useRoute, useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { playerTrainingAPI } from '../../api/playerClient';
import { useTheme } from '../../theme/ThemeProvider';
import { ThemeTokens } from '../../theme/tokens';
import { fonts } from '../../theme/typography';
import { ScreenBackground } from '../../theme/components';
import { renderReport } from '../../utils/renderReport';
import { buildPdfFileName } from '../../utils/buildReportPdf';
import { usePlayerAuth } from '../../context/PlayerAuthContext';

interface CoachTraining {
  id: number;
  program_text: string | null;
  priorities: string[] | null;
  coach_name: string | null;
  created_at: string;
}

export default function PlayerCoachTrainingDetailScreen() {
  const route = useRoute<any>();
  const navigation = useNavigation<any>();
  const { trainingId } = route.params;
  const { playerUser } = usePlayerAuth();
  const { t } = useTheme();
  const styles = makeStyles(t);

  const [training, setTraining] = useState<CoachTraining | null>(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    playerTrainingAPI.getCoachSent(trainingId)
      .then((tr: CoachTraining) => setTraining(tr))
      .catch(() => setTraining(null))
      .finally(() => setLoading(false));
  }, [trainingId]);

  const exportProgram = async () => {
    if (!training?.program_text) return;
    setExporting(true);
    try {
      const sanitize = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
      const date = new Date(training.created_at).toLocaleDateString();
      const bodyLines = training.program_text.split('\n').map(l => {
        const trimmed = l.trim();
        if (!trimmed) return '<div style="height:6px"></div>';
        const isHead = /^[A-Z0-9][A-Z0-9\s/&\-—().,':]+$/.test(trimmed.replace(/:$/, '')) || trimmed.endsWith(':');
        const clean = sanitize(trimmed.replace(/^#{1,6}\s*/, '').replace(/\*\*/g, '').replace(/^\s*[-*•·]\s+/, '• '));
        return isHead ? `<h3>${clean}</h3>` : `<p>${clean}</p>`;
      }).join('');
      const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>
        @page { margin: 18mm 16mm; }
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1f2937; font-size: 13px; line-height: 1.6; }
        h1 { font-size: 22px; font-weight: 900; color: #0f172a; margin-bottom: 2px; }
        h3 { font-size: 15px; font-weight: 800; color: #111; margin-top: 18px; border-bottom: 1px solid #cbd5e1; padding-bottom: 3px; }
        p { margin: 4px 0; }
      </style></head><body>
        <h1>BloomPrint — Training Program</h1>
        <p style="color:#555;margin-top:0">${date}${training.coach_name ? ` · From ${sanitize(training.coach_name)}` : ''}</p>
        ${bodyLines}
        <div style="margin-top:36px;font-size:11px;color:#999;border-top:1px solid #eee;padding-top:10px">Generated by BloomPrint</div>
      </body></html>`;
      const { uri } = await Print.printToFileAsync({ html });
      const dest = FileSystem.cacheDirectory
        + buildPdfFileName('Training Program', playerUser?.name ?? 'Player', new Date(training.created_at)) + '.pdf';
      await FileSystem.copyAsync({ from: uri, to: dest });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(dest, { mimeType: 'application/pdf', dialogTitle: 'Training Program' });
      } else {
        await Print.printAsync({ html });
      }
    } catch (e: any) {
      Alert.alert('Export Error', e?.message ?? 'Could not export program');
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <ScreenBackground>
        <View style={styles.center}>
          <ActivityIndicator color={t.positive} size="large" />
        </View>
      </ScreenBackground>
    );
  }

  if (!training) {
    return (
      <ScreenBackground>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Ionicons name="chevron-back" size={24} color={t.ink} />
          </TouchableOpacity>
        </View>
        <View style={styles.center}>
          <Text style={{ color: t.ink }}>Training program not found</Text>
        </View>
      </ScreenBackground>
    );
  }

  return (
    <ScreenBackground>
      <ScrollView style={styles.container} contentContainerStyle={{ paddingBottom: 60 }}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Ionicons name="chevron-back" size={24} color={t.ink} />
          </TouchableOpacity>
          <View style={{ flex: 1, marginLeft: 12 }}>
            <Text style={styles.title}>Training Program</Text>
            <Text style={styles.sub}>
              {new Date(training.created_at).toLocaleDateString()}
              {training.coach_name ? ` · From ${training.coach_name}` : ''}
            </Text>
          </View>
        </View>

        {training.priorities && training.priorities.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionLabel}>Priorities</Text>
            <View style={styles.programBox}>
              {training.priorities.map((p, i) => (
                <View key={i} style={styles.priorityRow}>
                  <View style={styles.priorityDot} />
                  <Text style={styles.priorityText}>{p}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Program</Text>
          <View style={styles.programBox}>
            {training.program_text ? (
              renderReport(training.program_text, { heading: t.ink, body: t.inkSoft })
            ) : (
              <View style={styles.generatingBox}>
                <ActivityIndicator color={t.positive} />
                <Text style={styles.generatingText}>Generating your program...</Text>
              </View>
            )}
          </View>
        </View>

        {training.program_text ? (
          <View style={styles.section}>
            <TouchableOpacity style={styles.exportBtn} onPress={exportProgram} disabled={exporting}>
              {exporting
                ? <ActivityIndicator color={t.ink} />
                : <><Ionicons name="share-outline" size={18} color={t.ink} /><Text style={styles.exportBtnText}>Export — Print or Send</Text></>}
            </TouchableOpacity>
          </View>
        ) : null}
      </ScrollView>
    </ScreenBackground>
  );
}

const makeStyles = (t: ThemeTokens) => StyleSheet.create({
  container: { flex: 1, backgroundColor: 'transparent' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', padding: 20, paddingTop: 56 },
  title: { color: t.ink, fontSize: 16, fontFamily: fonts[900] },
  sub: { color: t.muted2, fontSize: 11, marginTop: 2 },
  section: { paddingHorizontal: 20, marginTop: 24 },
  sectionLabel: {
    color: t.label, fontSize: 11, fontFamily: fonts[700], letterSpacing: 1,
    textTransform: 'uppercase', marginBottom: 12,
  },
  programBox: { backgroundColor: t.card, borderRadius: 12, padding: 16, borderWidth: 1, borderColor: t.cardBorder },
  priorityRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  priorityDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: t.accent },
  priorityText: { color: t.inkSoft, fontSize: 13.5, flex: 1 },
  generatingBox: { alignItems: 'center', paddingVertical: 32, gap: 12 },
  generatingText: { color: t.muted2, fontSize: 13 },
  exportBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    backgroundColor: t.chip, borderRadius: 12, paddingVertical: 15,
    borderWidth: 1, borderColor: t.cta2Border,
  },
  exportBtnText: { color: t.ink, fontSize: 15, fontFamily: fonts[800] },
});
