#!/usr/bin/env python3
"""Compile the app's notification strings into a Python module the API can read.

WHY THIS EXISTS

Every in-app notification is stored as an i18n key plus params, and the client
renders it in the reader's language from mobile/src/i18n/locales. Emailing the
same event needs the same words in the same language — and the API image does
not contain mobile/ at all (see .dockerignore), so at runtime the packs are not
there to read.

The alternative was a second set of email copy, written and translated
separately for thirty-odd events. That is the same message written twice in
twenty-five languages, and the two halves drift the first time either is
edited: the app would say one thing and the inbox another about the same event.

So the packs stay the single source and this compiles the part the server needs
into api/notif_copy.py, which is committed. Re-run it after touching notifs,
reportTypes or jobs.kinds in any pack:

    python3 scripts/i18n/build_notif_copy.py

api/emails.py refuses to start on a mismatch, using the digest written below.
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PACKS = os.path.join(ROOT, "mobile", "src", "i18n", "locales")
OUT = os.path.join(ROOT, "api", "notif_copy.py")

# Kept in step with LANGS in api/emails.py, and in the same order, so the
# generated file reads the way the rest of the email code does.
LANGS = ["en", "es", "fr", "pt", "it", "de", "nl", "sv", "pl", "ru", "uk",
         "sr", "hr", "tr", "ro", "el", "lt", "ar", "he", "hi", "ka", "ja",
         "ko", "zh", "tl"]


def load(lang: str) -> dict:
    with open(os.path.join(PACKS, f"{lang}.json"), encoding="utf-8") as f:
        return json.load(f)


def collect() -> tuple[dict, dict, dict]:
    notifs: dict[str, dict[str, list[str]]] = {}
    report_types: dict[str, dict[str, str]] = {}
    job_kinds: dict[str, dict[str, str]] = {}

    english = load("en")
    for key, val in english["notifs"].items():
        if not (isinstance(val, dict) and {"title", "body"} <= set(val)):
            sys.exit(f"notifs.{key} in en.json is not title+body: {val!r}")
        notifs[key] = {}

    for lang in LANGS:
        pack = load(lang)
        for key in notifs:
            val = pack.get("notifs", {}).get(key)
            if isinstance(val, dict) and {"title", "body"} <= set(val):
                notifs[key][lang] = [val["title"], val["body"]]
            # A pack missing the key simply has no entry: the reader falls back
            # to English, the same way the app does.
        report_types[lang] = dict(pack.get("reportTypes", {}))
        job_kinds[lang] = dict(pack.get("jobs", {}).get("kinds", {}))

    return notifs, report_types, job_kinds


def digest() -> str:
    """A fingerprint of the source strings, so a stale build is detectable.

    Over the three namespaces the server uses, not the whole pack: an unrelated
    edit to a button label should not make this file look out of date.
    """
    h = hashlib.sha256()
    for lang in LANGS:
        pack = load(lang)
        h.update(json.dumps(pack.get("notifs", {}), sort_keys=True,
                            ensure_ascii=False).encode())
        h.update(json.dumps(pack.get("reportTypes", {}), sort_keys=True,
                            ensure_ascii=False).encode())
        h.update(json.dumps(pack.get("jobs", {}).get("kinds", {}),
                            sort_keys=True, ensure_ascii=False).encode())
    return h.hexdigest()


def render(notifs, report_types, job_kinds, fingerprint) -> str:
    out = [
        '"""The app\'s notification strings, compiled for the API. DO NOT EDIT.',
        "",
        "Generated by scripts/i18n/build_notif_copy.py from",
        "mobile/src/i18n/locales/*.json. Edit the packs and re-run that, never",
        "this file: it is overwritten, and the point of it is that the email and",
        "the in-app notification cannot come to say different things.",
        '"""',
        "",
        f'SOURCE_DIGEST = "{fingerprint}"',
        "",
        "# key -> language -> (title, body). Placeholders are the app's own",
        "# {{name}} form, interpolated by api/emails.py.",
        "NOTIF_COPY: dict[str, dict[str, tuple[str, str]]] = {",
    ]
    for key in sorted(notifs):
        out.append(f"    {key!r}: {{")
        for lang in LANGS:
            pair = notifs[key].get(lang)
            if pair:
                out.append(f"        {lang!r}: ({pair[0]!r}, {pair[1]!r}),")
        out.append("    },")
    out.append("}")
    out.append("")
    out.append("# Params the row carries as API enums rather than as words, because the")
    out.append("# writer does not know who will read it. Same two the client localizes.")
    out.append("REPORT_TYPES: dict[str, dict[str, str]] = {")
    for lang in LANGS:
        out.append(f"    {lang!r}: {report_types[lang]!r},")
    out.append("}")
    out.append("")
    out.append("JOB_KINDS: dict[str, dict[str, str]] = {")
    for lang in LANGS:
        out.append(f"    {lang!r}: {job_kinds[lang]!r},")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    notifs, report_types, job_kinds = collect()
    text = render(notifs, report_types, job_kinds, digest())
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    languages = {lang for by_lang in notifs.values() for lang in by_lang}
    print(f"wrote {OUT}")
    print(f"  {len(notifs)} notification types across {len(languages)} languages")
    gaps = [f"{k}/{lang}" for k in notifs for lang in LANGS
            if lang not in notifs[k]]
    print(f"  gaps (fall back to English): {len(gaps)}"
          + (f" e.g. {gaps[:4]}" if gaps else ""))


if __name__ == "__main__":
    main()
