import os
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from ..database import get_db
from ..auth import get_current_coach
from .. import models, schemas

router = APIRouter(prefix="/training", tags=["training"])


class RegenerateRequest(BaseModel):
    feedback: str


@router.post("", response_model=schemas.TrainingOut)
async def generate_training(
    body: schemas.TrainingRequest,
    db: Session = Depends(get_db),
    coach: models.Coach = Depends(get_current_coach),
):
    player = db.get(models.Player, body.player_id)
    if not player:
        raise HTTPException(status_code=404, detail="Player not found")

    eval_record = None
    if body.evaluation_id:
        eval_record = db.get(models.Evaluation, body.evaluation_id)
        if not eval_record or eval_record.player_id != body.player_id:
            raise HTTPException(status_code=404, detail="Evaluation not found for this player")

    # Find latest overall_grade from player's evaluations
    latest_grade: float | None = None
    for ev in sorted(player.evaluations, key=lambda e: e.created_at, reverse=True):
        if ev.overall_grade is not None:
            latest_grade = ev.overall_grade
            break

    # Build context from the most recent eval if available
    focus = body.focus_prompt or ""
    if eval_record and eval_record.report_text:
        focus = f"Base this training program on the following player evaluation:\n\n{eval_record.report_text[:3000]}\n\n{focus}"
    elif player.notes:
        focus = f"Player notes: {player.notes}\n\n{focus}"

    import sys
    sys.path.insert(0, ".")
    from video_vision.bim import build_prompt
    import anthropic

    prompt = build_prompt(
        "training_program",
        coach.program_name,
        player.competition_level,
        coach.weight,
        player.name,
    )
    # Explicitly include height and rating
    prompt += f"\n\nPLAYER METRICS:\nHEIGHT: {player.height or 'Not recorded'}\nCURRENT RATING: {f'{latest_grade}/10' if latest_grade is not None else 'Not evaluated'}"
    if focus:
        prompt += f"\n\nCOACH CONTEXT:\n{focus}"
    prompt += "\n\nIMPORTANT: Do NOT use ## headers or ** bold markers in your response. Use plain text with clear section labels instead."

    client = anthropic.Anthropic()
    response = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=3000,
        messages=[{"role": "user", "content": prompt}],
    )
    program_text = response.content[0].text

    # Extract ordered priorities from the program text
    import re
    priorities: list[str] = []
    m = re.search(r"KPI TARGETS(.*?)(?:CORRECTABLE|PROGRESS|$)", program_text, re.DOTALL | re.IGNORECASE)
    if m:
        for line in m.group(1).splitlines():
            line = re.sub(r"^[-·*\d\.\s↑↓]+", "", line).strip()
            if line:
                priorities.append(line)

    session = models.TrainingSession(
        player_id=body.player_id,
        coach_id=coach.id,
        evaluation_id=body.evaluation_id,
        program_text=program_text,
        priorities=priorities[:6],
    )
    db.add(session)
    db.commit()
    db.refresh(session)
    return session


@router.post("/{training_id}/send-to-player")
def send_training_to_player(
    training_id: int,
    db: Session = Depends(get_db),
    coach: models.Coach = Depends(get_current_coach),
):
    """Send a training session notification to the linked player user."""
    session = db.get(models.TrainingSession, training_id)
    if not session:
        raise HTTPException(status_code=404, detail="Training session not found")
    player = db.get(models.Player, session.player_id)
    if not player:
        raise HTTPException(status_code=404, detail="Player not found")
    if not player.player_user:
        raise HTTPException(status_code=400, detail="Player is not linked to a player account yet")
    notif = models.PlayerNotification(
        player_user_id=player.player_user.id,
        type="training_shared",
        title="Training Program Sent",
        body=f"{coach.name} sent you a training program. Check your training tab.",
        ref_id=training_id,
    )
    db.add(notif)
    db.commit()
    return {"ok": True, "player_name": player.name}


@router.get("/player/{player_id}", response_model=list[schemas.TrainingOut])
def list_training(
    player_id: int,
    db: Session = Depends(get_db),
    coach: models.Coach = Depends(get_current_coach),
):
    return db.query(models.TrainingSession).filter_by(player_id=player_id).all()


@router.get("/recent", response_model=list[schemas.TrainingOut])
def recent_training(
    limit: int = 30,
    db: Session = Depends(get_db),
    coach: models.Coach = Depends(get_current_coach),
):
    """Get recent training sessions generated by this coach."""
    return (
        db.query(models.TrainingSession)
        .filter_by(coach_id=coach.id)
        .order_by(models.TrainingSession.id.desc())
        .limit(limit)
        .all()
    )


@router.post("/players/{player_id}/regenerate", response_model=schemas.TrainingOut)
async def regenerate_training(
    player_id: int,
    body: RegenerateRequest,
    db: Session = Depends(get_db),
    coach: models.Coach = Depends(get_current_coach),
):
    """Regenerate training program with coach feedback, replacing the latest session."""
    player = db.get(models.Player, player_id)
    if not player:
        raise HTTPException(status_code=404, detail="Player not found")

    # Get the latest training session for this player
    latest = (
        db.query(models.TrainingSession)
        .filter_by(player_id=player_id)
        .order_by(models.TrainingSession.id.desc())
        .first()
    )

    # Find latest overall_grade
    latest_grade: float | None = None
    for ev in sorted(player.evaluations, key=lambda e: e.created_at, reverse=True):
        if ev.overall_grade is not None:
            latest_grade = ev.overall_grade
            break

    prior_text = latest.program_text if latest else "No prior program."

    prompt = (
        f"You are the BloomPrint Basketball Intelligence Model.\n"
        f"Here is the current training program for {player.name}:\n\n"
        f"{prior_text[:3000]}\n\n"
        f"PLAYER METRICS:\n"
        f"HEIGHT: {player.height or 'Not recorded'}\n"
        f"CURRENT RATING: {f'{latest_grade}/10' if latest_grade is not None else 'Not evaluated'}\n\n"
        f"COACH FEEDBACK:\n{body.feedback}\n\n"
        "Update the training program incorporating the coach feedback. Keep the same structure but adjust focus areas, drills, and weekly plan based on the feedback.\n"
        "IMPORTANT: Do NOT use ## headers or ** bold markers. Use plain text section labels."
    )

    import anthropic
    client = anthropic.Anthropic()
    response = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=3000,
        messages=[{"role": "user", "content": prompt}],
    )
    program_text = response.content[0].text

    import re
    priorities: list[str] = []
    m = re.search(r"KPI TARGETS(.*?)(?:CORRECTABLE|PROGRESS|$)", program_text, re.DOTALL | re.IGNORECASE)
    if m:
        for line in m.group(1).splitlines():
            line = re.sub(r"^[-·*\d\.\s↑↓]+", "", line).strip()
            if line:
                priorities.append(line)

    if latest:
        latest.program_text = program_text
        latest.priorities = priorities[:6]
        db.commit()
        db.refresh(latest)
        return latest
    else:
        session = models.TrainingSession(
            player_id=player_id,
            coach_id=coach.id,
            program_text=program_text,
            priorities=priorities[:6],
        )
        db.add(session)
        db.commit()
        db.refresh(session)
        return session
