"""Subject and body for each event, per language.

One short sentence each. The greeting, the link and the footer come from the
shell in emails.py, so nothing here repeats what every message already says.

Placeholders are filled from the same params the in-app notification carries,
so a notification and its email cannot describe the event differently.
"""

# event -> lang -> (subject, body)
EVENTS: dict[str, dict[str, tuple[str, str]]] = {}


EVENTS["staff_invite"] = {
    "en": ("{inviter} invited you to {team}",
           "{inviter} invited you to join the staff of {team} on BloomPrint."),
    "es": ("{inviter} te ha invitado a {team}",
           "{inviter} te ha invitado a formar parte del cuerpo técnico de {team} en BloomPrint."),
    "fr": ("{inviter} vous a invité à rejoindre {team}",
           "{inviter} vous a invité à rejoindre le staff de {team} sur BloomPrint."),
    "pt": ("{inviter} convidou-o para {team}",
           "{inviter} convidou-o para integrar a equipa técnica de {team} no BloomPrint."),
    "it": ("{inviter} ti ha invitato in {team}",
           "{inviter} ti ha invitato a entrare nello staff di {team} su BloomPrint."),
    "de": ("{inviter} hat dich zu {team} eingeladen",
           "{inviter} hat dich eingeladen, dem Trainerstab von {team} auf BloomPrint beizutreten."),
    "nl": ("{inviter} heeft je uitgenodigd voor {team}",
           "{inviter} heeft je uitgenodigd om deel uit te maken van de staf van {team} op BloomPrint."),
    "sv": ("{inviter} har bjudit in dig till {team}",
           "{inviter} har bjudit in dig till ledarstaben för {team} på BloomPrint."),
    "pl": ("{inviter} zaprosił Cię do {team}",
           "{inviter} zaprosił Cię do sztabu {team} w BloomPrint."),
    "ru": ("{inviter} приглашает вас в {team}",
           "{inviter} приглашает вас войти в тренерский штаб команды {team} в BloomPrint."),
    "uk": ("{inviter} запрошує вас до {team}",
           "{inviter} запрошує вас увійти до тренерського штабу команди {team} у BloomPrint."),
    "sr": ("{inviter} вас позива у {team}",
           "{inviter} вас позива да се придружите стручном штабу тима {team} на BloomPrint-у."),
    "hr": ("{inviter} vas poziva u {team}",
           "{inviter} vas poziva da se pridružite stručnom stožeru tima {team} na BloomPrintu."),
    "tr": ("{inviter} sizi {team} takımına davet etti",
           "{inviter} sizi BloomPrint'te {team} teknik ekibine katılmaya davet etti."),
    "ro": ("{inviter} te-a invitat la {team}",
           "{inviter} te-a invitat să faci parte din staff-ul echipei {team} pe BloomPrint."),
    "el": ("Ο/Η {inviter} σε προσκάλεσε στην {team}",
           "Ο/Η {inviter} σε προσκάλεσε να μπεις στο προπονητικό τιμ της {team} στο BloomPrint."),
    "lt": ("{inviter} pakvietė jus į {team}",
           "{inviter} pakvietė jus prisijungti prie {team} trenerių štabo BloomPrint sistemoje."),
    "ar": ("دعاك {inviter} للانضمام إلى {team}",
           "دعاك {inviter} للانضمام إلى الجهاز الفني لفريق {team} على BloomPrint."),
    "he": ("{inviter} הזמין אותך ל־{team}",
           "{inviter} הזמין אותך להצטרף לצוות המקצועי של {team} ב־BloomPrint."),
    "hi": ("{inviter} ने आपको {team} में आमंत्रित किया",
           "{inviter} ने आपको BloomPrint पर {team} के कोचिंग स्टाफ़ में शामिल होने के लिए आमंत्रित किया है।"),
    "ka": ("{inviter}-მა მოგიწვიათ {team}-ში",
           "{inviter}-მა მოგიწვიათ {team}-ის სამწვრთნელო შტაბში BloomPrint-ზე."),
    "ja": ("{inviter} さんが {team} に招待しました",
           "{inviter} さんが BloomPrint の {team} のスタッフとしてあなたを招待しました。"),
    "ko": ("{inviter}님이 {team}에 초대했습니다",
           "{inviter}님이 BloomPrint에서 {team} 코칭 스태프로 초대했습니다."),
    "zh": ("{inviter} 邀请你加入 {team}",
           "{inviter} 邀请你加入 BloomPrint 上 {team} 的教练组。"),
    "tl": ("Inimbitahan ka ni {inviter} sa {team}",
           "Inimbitahan ka ni {inviter} na sumali sa staff ng {team} sa BloomPrint."),
}


EVENTS["team_join_request"] = {
    "en": ("{coach} asked to join {team}",
           "{coach} has asked to join {team}. You can approve or decline the request."),
    "es": ("{coach} ha pedido unirse a {team}",
           "{coach} ha pedido unirse a {team}. Puedes aceptar o rechazar la solicitud."),
    "fr": ("{coach} demande à rejoindre {team}",
           "{coach} demande à rejoindre {team}. Vous pouvez accepter ou refuser la demande."),
    "pt": ("{coach} pediu para entrar em {team}",
           "{coach} pediu para entrar em {team}. Pode aceitar ou recusar o pedido."),
    "it": ("{coach} ha chiesto di entrare in {team}",
           "{coach} ha chiesto di entrare in {team}. Puoi accettare o rifiutare la richiesta."),
    "de": ("{coach} möchte {team} beitreten",
           "{coach} möchte {team} beitreten. Du kannst die Anfrage annehmen oder ablehnen."),
    "nl": ("{coach} wil zich aansluiten bij {team}",
           "{coach} wil zich aansluiten bij {team}. Je kunt het verzoek goedkeuren of afwijzen."),
    "sv": ("{coach} vill gå med i {team}",
           "{coach} vill gå med i {team}. Du kan godkänna eller avslå förfrågan."),
    "pl": ("{coach} prosi o dołączenie do {team}",
           "{coach} prosi o dołączenie do {team}. Możesz zaakceptować lub odrzucić prośbę."),
    "ru": ("{coach} просит принять в {team}",
           "{coach} просит принять его в команду {team}. Вы можете одобрить или отклонить запрос."),
    "uk": ("{coach} просить прийняти до {team}",
           "{coach} просить прийняти його до команди {team}. Ви можете схвалити або відхилити запит."),
    "sr": ("{coach} тражи да се придружи тиму {team}",
           "{coach} тражи да се придружи тиму {team}. Можете одобрити или одбити захтев."),
    "hr": ("{coach} traži pridruživanje timu {team}",
           "{coach} traži pridruživanje timu {team}. Možete odobriti ili odbiti zahtjev."),
    "tr": ("{coach} {team} takımına katılmak istiyor",
           "{coach} {team} takımına katılmak istiyor. İsteği onaylayabilir veya reddedebilirsiniz."),
    "ro": ("{coach} cere să se alăture echipei {team}",
           "{coach} cere să se alăture echipei {team}. Poți aproba sau respinge cererea."),
    "el": ("Ο/Η {coach} ζήτησε να μπει στην {team}",
           "Ο/Η {coach} ζήτησε να μπει στην {team}. Μπορείς να εγκρίνεις ή να απορρίψεις το αίτημα."),
    "lt": ("{coach} prašo prisijungti prie {team}",
           "{coach} prašo prisijungti prie {team}. Galite patvirtinti arba atmesti prašymą."),
    "ar": ("طلب {coach} الانضمام إلى {team}",
           "طلب {coach} الانضمام إلى {team}. يمكنك قبول الطلب أو رفضه."),
    "he": ("{coach} ביקש להצטרף ל־{team}",
           "{coach} ביקש להצטרף ל־{team}. אפשר לאשר או לדחות את הבקשה."),
    "hi": ("{coach} ने {team} में शामिल होने का अनुरोध किया",
           "{coach} ने {team} में शामिल होने का अनुरोध किया है। आप इसे स्वीकार या अस्वीकार कर सकते हैं।"),
    "ka": ("{coach} ითხოვს {team}-ში გაწევრიანებას",
           "{coach} ითხოვს {team}-ში გაწევრიანებას. შეგიძლიათ დაადასტუროთ ან უარყოთ მოთხოვნა."),
    "ja": ("{coach} さんが {team} への参加を希望しています",
           "{coach} さんが {team} への参加を希望しています。承認または却下できます。"),
    "ko": ("{coach}님이 {team} 합류를 요청했습니다",
           "{coach}님이 {team} 합류를 요청했습니다. 요청을 승인하거나 거절할 수 있습니다."),
    "zh": ("{coach} 申请加入 {team}",
           "{coach} 申请加入 {team}。你可以批准或拒绝该申请。"),
    "tl": ("Humiling si {coach} na sumali sa {team}",
           "Humiling si {coach} na sumali sa {team}. Maaari mong aprubahan o tanggihan ang hiling."),
}


EVENTS["team_join_approved"] = {
    "en": ("You're in — {team}",
           "Your request to join {team} was approved. You now have access to the team."),
    "es": ("Ya estás dentro — {team}",
           "Tu solicitud para unirte a {team} ha sido aceptada. Ya tienes acceso al equipo."),
    "fr": ("C'est bon — {team}",
           "Votre demande pour rejoindre {team} a été acceptée. Vous avez désormais accès à l'équipe."),
    "pt": ("Está dentro — {team}",
           "O seu pedido para entrar em {team} foi aceite. Já tem acesso à equipa."),
    "it": ("Sei dentro — {team}",
           "La tua richiesta di entrare in {team} è stata accettata. Ora hai accesso alla squadra."),
    "de": ("Du bist dabei — {team}",
           "Deine Anfrage für {team} wurde angenommen. Du hast jetzt Zugriff auf das Team."),
    "nl": ("Je zit erbij — {team}",
           "Je verzoek om je aan te sluiten bij {team} is goedgekeurd. Je hebt nu toegang tot het team."),
    "sv": ("Du är med — {team}",
           "Din förfrågan om att gå med i {team} har godkänts. Du har nu tillgång till laget."),
    "pl": ("Jesteś w zespole — {team}",
           "Twoja prośba o dołączenie do {team} została zaakceptowana. Masz teraz dostęp do zespołu."),
    "ru": ("Вы в команде — {team}",
           "Ваш запрос на вступление в {team} одобрен. Теперь у вас есть доступ к команде."),
    "uk": ("Ви в команді — {team}",
           "Ваш запит на приєднання до {team} схвалено. Тепер ви маєте доступ до команди."),
    "sr": ("Примљени сте — {team}",
           "Ваш захтев за придруживање тиму {team} је одобрен. Сада имате приступ тиму."),
    "hr": ("Primljeni ste — {team}",
           "Vaš zahtjev za pridruživanje timu {team} je odobren. Sada imate pristup timu."),
    "tr": ("Katıldınız — {team}",
           "{team} takımına katılma isteğiniz onaylandı. Artık takıma erişebilirsiniz."),
    "ro": ("Ești în echipă — {team}",
           "Cererea ta de a te alătura echipei {team} a fost aprobată. Ai acum acces la echipă."),
    "el": ("Μπήκες — {team}",
           "Το αίτημά σου να μπεις στην {team} εγκρίθηκε. Έχεις πλέον πρόσβαση στην ομάδα."),
    "lt": ("Jūs komandoje — {team}",
           "Jūsų prašymas prisijungti prie {team} patvirtintas. Dabar turite prieigą prie komandos."),
    "ar": ("تمت إضافتك — {team}",
           "تمت الموافقة على طلبك للانضمام إلى {team}. أصبح لديك الآن حق الوصول إلى الفريق."),
    "he": ("אתה בפנים — {team}",
           "הבקשה שלך להצטרף ל־{team} אושרה. יש לך כעת גישה לקבוצה."),
    "hi": ("आप शामिल हो गए — {team}",
           "{team} में शामिल होने का आपका अनुरोध स्वीकार कर लिया गया है। अब आपके पास टीम की पहुँच है।"),
    "ka": ("თქვენ ხართ გუნდში — {team}",
           "თქვენი მოთხოვნა {team}-ში გაწევრიანებაზე დამტკიცდა. ახლა გაქვთ წვდომა გუნდზე."),
    "ja": ("参加が承認されました — {team}",
           "{team} への参加リクエストが承認されました。チームにアクセスできます。"),
    "ko": ("합류되었습니다 — {team}",
           "{team} 합류 요청이 승인되었습니다. 이제 팀에 접근할 수 있습니다."),
    "zh": ("你已加入 — {team}",
           "你加入 {team} 的申请已通过。现在你可以访问该球队了。"),
    "tl": ("Kasali ka na — {team}",
           "Naaprubahan ang hiling mong sumali sa {team}. May access ka na sa koponan."),
}


EVENTS["team_join_rejected"] = {
    "en": ("Your request to join {team}",
           "Your request to join {team} wasn't approved this time."),
    "es": ("Tu solicitud para unirte a {team}",
           "Tu solicitud para unirte a {team} no ha sido aceptada esta vez."),
    "fr": ("Votre demande pour rejoindre {team}",
           "Votre demande pour rejoindre {team} n'a pas été acceptée cette fois."),
    "pt": ("O seu pedido para entrar em {team}",
           "O seu pedido para entrar em {team} não foi aceite desta vez."),
    "it": ("La tua richiesta di entrare in {team}",
           "La tua richiesta di entrare in {team} non è stata accettata questa volta."),
    "de": ("Deine Anfrage für {team}",
           "Deine Anfrage für {team} wurde diesmal nicht angenommen."),
    "nl": ("Je verzoek voor {team}",
           "Je verzoek om je aan te sluiten bij {team} is deze keer niet goedgekeurd."),
    "sv": ("Din förfrågan om {team}",
           "Din förfrågan om att gå med i {team} godkändes inte den här gången."),
    "pl": ("Twoja prośba o dołączenie do {team}",
           "Twoja prośba o dołączenie do {team} nie została tym razem zaakceptowana."),
    "ru": ("Ваш запрос в {team}",
           "Ваш запрос на вступление в {team} на этот раз не был одобрен."),
    "uk": ("Ваш запит до {team}",
           "Ваш запит на приєднання до {team} цього разу не було схвалено."),
    "sr": ("Ваш захтев за {team}",
           "Ваш захтев за придруживање тиму {team} овог пута није одобрен."),
    "hr": ("Vaš zahtjev za {team}",
           "Vaš zahtjev za pridruživanje timu {team} ovaj put nije odobren."),
    "tr": ("{team} için isteğiniz",
           "{team} takımına katılma isteğiniz bu kez onaylanmadı."),
    "ro": ("Cererea ta pentru {team}",
           "Cererea ta de a te alătura echipei {team} nu a fost aprobată de această dată."),
    "el": ("Το αίτημά σου για την {team}",
           "Το αίτημά σου να μπεις στην {team} δεν εγκρίθηκε αυτή τη φορά."),
    "lt": ("Jūsų prašymas dėl {team}",
           "Jūsų prašymas prisijungti prie {team} šįkart nebuvo patvirtintas."),
    "ar": ("طلبك للانضمام إلى {team}",
           "لم تتم الموافقة على طلبك للانضمام إلى {team} هذه المرة."),
    "he": ("הבקשה שלך להצטרף ל־{team}",
           "הבקשה שלך להצטרף ל־{team} לא אושרה הפעם."),
    "hi": ("{team} में शामिल होने का आपका अनुरोध",
           "{team} में शामिल होने का आपका अनुरोध इस बार स्वीकार नहीं किया गया।"),
    "ka": ("თქვენი მოთხოვნა {team}-ზე",
           "თქვენი მოთხოვნა {team}-ში გაწევრიანებაზე ამჯერად არ დამტკიცდა."),
    "ja": ("{team} への参加リクエストについて",
           "{team} への参加リクエストは今回は承認されませんでした。"),
    "ko": ("{team} 합류 요청 안내",
           "{team} 합류 요청이 이번에는 승인되지 않았습니다."),
    "zh": ("你加入 {team} 的申请",
           "你加入 {team} 的申请这次未获通过。"),
    "tl": ("Ang hiling mong sumali sa {team}",
           "Hindi naaprubahan sa pagkakataong ito ang hiling mong sumali sa {team}."),
}


EVENTS["player_link_request"] = {
    "en": ("{player} wants to link to your roster",
           "{player} has asked to link their account to a player on your roster."),
    "es": ("{player} quiere vincularse a tu plantilla",
           "{player} ha pedido vincular su cuenta a un jugador de tu plantilla."),
    "fr": ("{player} souhaite se lier à votre effectif",
           "{player} a demandé à lier son compte à un joueur de votre effectif."),
    "pt": ("{player} quer associar-se ao seu plantel",
           "{player} pediu para associar a sua conta a um jogador do seu plantel."),
    "it": ("{player} vuole collegarsi alla tua rosa",
           "{player} ha chiesto di collegare il proprio account a un giocatore della tua rosa."),
    "de": ("{player} möchte sich mit deinem Kader verknüpfen",
           "{player} möchte das eigene Konto mit einem Spieler in deinem Kader verknüpfen."),
    "nl": ("{player} wil koppelen aan je selectie",
           "{player} heeft gevraagd om het account te koppelen aan een speler in je selectie."),
    "sv": ("{player} vill kopplas till din trupp",
           "{player} har bett om att koppla sitt konto till en spelare i din trupp."),
    "pl": ("{player} chce połączyć się z Twoim składem",
           "{player} poprosił o połączenie swojego konta z zawodnikiem z Twojego składu."),
    "ru": ("{player} хочет привязаться к вашему составу",
           "{player} просит привязать свою учётную запись к игроку из вашего состава."),
    "uk": ("{player} хоче прив'язатися до вашого складу",
           "{player} просить прив'язати свій обліковий запис до гравця з вашого складу."),
    "sr": ("{player} жели да се повеже са вашим тимом",
           "{player} тражи да повеже свој налог са играчем из вашег тима."),
    "hr": ("{player} se želi povezati s vašim sastavom",
           "{player} traži povezivanje svojeg računa s igračem iz vašeg sastava."),
    "tr": ("{player} kadronuza bağlanmak istiyor",
           "{player} hesabını kadronuzdaki bir oyuncuya bağlamak istiyor."),
    "ro": ("{player} vrea să se lege de lotul tău",
           "{player} a cerut să își lege contul de un jucător din lotul tău."),
    "el": ("Ο/Η {player} θέλει να συνδεθεί με το ρόστερ σου",
           "Ο/Η {player} ζήτησε να συνδέσει τον λογαριασμό του με παίκτη του ρόστερ σου."),
    "lt": ("{player} nori susieti su jūsų sudėtimi",
           "{player} paprašė susieti savo paskyrą su žaidėju iš jūsų sudėties."),
    "ar": ("يريد {player} الارتباط بقائمتك",
           "طلب {player} ربط حسابه بلاعب في قائمتك."),
    "he": ("{player} מבקש להתחבר לסגל שלך",
           "{player} ביקש לקשר את החשבון שלו לשחקן בסגל שלך."),
    "hi": ("{player} आपकी रोस्टर से जुड़ना चाहता है",
           "{player} ने अपने खाते को आपकी रोस्टर के किसी खिलाड़ी से जोड़ने का अनुरोध किया है।"),
    "ka": ("{player}-ს სურს დაკავშირება თქვენს შემადგენლობასთან",
           "{player}-მა მოითხოვა თავისი ანგარიშის დაკავშირება თქვენი შემადგენლობის მოთამაშესთან."),
    "ja": ("{player} さんがロスター連携を希望しています",
           "{player} さんが自分のアカウントをあなたのロスターの選手と連携させたいと申請しました。"),
    "ko": ("{player}님이 로스터 연결을 요청했습니다",
           "{player}님이 자신의 계정을 로스터의 선수와 연결하기를 요청했습니다."),
    "zh": ("{player} 想关联到你的球员名单",
           "{player} 申请将其账号关联到你名单中的一名球员。"),
    "tl": ("Gustong mag-link ni {player} sa roster mo",
           "Humiling si {player} na i-link ang kanyang account sa isang manlalaro sa roster mo."),
}


EVENTS["player_link_approved"] = {
    "en": ("You're linked to {team}",
           "Your account is now linked to your player profile on {team}."),
    "es": ("Ya estás vinculado a {team}",
           "Tu cuenta ya está vinculada a tu perfil de jugador en {team}."),
    "fr": ("Vous êtes lié à {team}",
           "Votre compte est désormais lié à votre profil de joueur dans {team}."),
    "pt": ("Está associado a {team}",
           "A sua conta está agora associada ao seu perfil de jogador em {team}."),
    "it": ("Sei collegato a {team}",
           "Il tuo account è ora collegato al tuo profilo giocatore in {team}."),
    "de": ("Du bist mit {team} verknüpft",
           "Dein Konto ist jetzt mit deinem Spielerprofil bei {team} verknüpft."),
    "nl": ("Je bent gekoppeld aan {team}",
           "Je account is nu gekoppeld aan je spelersprofiel bij {team}."),
    "sv": ("Du är kopplad till {team}",
           "Ditt konto är nu kopplat till din spelarprofil i {team}."),
    "pl": ("Jesteś połączony z {team}",
           "Twoje konto jest teraz połączone z Twoim profilem zawodnika w {team}."),
    "ru": ("Вы привязаны к {team}",
           "Ваша учётная запись привязана к вашему профилю игрока в {team}."),
    "uk": ("Вас прив'язано до {team}",
           "Ваш обліковий запис прив'язано до вашого профілю гравця в {team}."),
    "sr": ("Повезани сте са {team}",
           "Ваш налог је сада повезан са вашим играчким профилом у тиму {team}."),
    "hr": ("Povezani ste s {team}",
           "Vaš račun sada je povezan s vašim igračkim profilom u timu {team}."),
    "tr": ("{team} ile bağlantılısınız",
           "Hesabınız artık {team} takımındaki oyuncu profilinizle bağlantılı."),
    "ro": ("Ești conectat la {team}",
           "Contul tău este acum conectat la profilul tău de jucător din {team}."),
    "el": ("Συνδέθηκες με την {team}",
           "Ο λογαριασμός σου συνδέθηκε με το προφίλ παίκτη σου στην {team}."),
    "lt": ("Esate susietas su {team}",
           "Jūsų paskyra dabar susieta su jūsų žaidėjo profiliu komandoje {team}."),
    "ar": ("تم ربطك بـ {team}",
           "أصبح حسابك مرتبطًا الآن بملفك كلاعب في {team}."),
    "he": ("אתה מקושר ל־{team}",
           "החשבון שלך מקושר כעת לפרופיל השחקן שלך ב־{team}."),
    "hi": ("आप {team} से जुड़ गए हैं",
           "आपका खाता अब {team} में आपके खिलाड़ी प्रोफ़ाइल से जुड़ गया है।"),
    "ka": ("თქვენ დაკავშირებული ხართ {team}-თან",
           "თქვენი ანგარიში ახლა დაკავშირებულია თქვენს მოთამაშის პროფილთან გუნდში {team}."),
    "ja": ("{team} と連携しました",
           "あなたのアカウントが {team} の選手プロフィールと連携されました。"),
    "ko": ("{team}에 연결되었습니다",
           "계정이 {team}의 선수 프로필과 연결되었습니다."),
    "zh": ("你已关联到 {team}",
           "你的账号已关联到你在 {team} 的球员档案。"),
    "tl": ("Naka-link ka na sa {team}",
           "Naka-link na ang account mo sa iyong player profile sa {team}."),
}


EVENTS["report_shared"] = {
    "en": ("{sender} shared a report with you",
           "{sender} shared a {report} with you on BloomPrint."),
    "es": ("{sender} ha compartido un informe contigo",
           "{sender} ha compartido un {report} contigo en BloomPrint."),
    "fr": ("{sender} a partagé un rapport avec vous",
           "{sender} a partagé un {report} avec vous sur BloomPrint."),
    "pt": ("{sender} partilhou um relatório consigo",
           "{sender} partilhou um {report} consigo no BloomPrint."),
    "it": ("{sender} ha condiviso un report con te",
           "{sender} ha condiviso un {report} con te su BloomPrint."),
    "de": ("{sender} hat einen Bericht mit dir geteilt",
           "{sender} hat einen {report} auf BloomPrint mit dir geteilt."),
    "nl": ("{sender} heeft een rapport met je gedeeld",
           "{sender} heeft een {report} met je gedeeld op BloomPrint."),
    "sv": ("{sender} delade en rapport med dig",
           "{sender} delade en {report} med dig på BloomPrint."),
    "pl": ("{sender} udostępnił Ci raport",
           "{sender} udostępnił Ci {report} w BloomPrint."),
    "ru": ("{sender} поделился с вами отчётом",
           "{sender} поделился с вами материалом «{report}» в BloomPrint."),
    "uk": ("{sender} поділився з вами звітом",
           "{sender} поділився з вами матеріалом «{report}» у BloomPrint."),
    "sr": ("{sender} је поделио извештај са вама",
           "{sender} је поделио {report} са вама на BloomPrint-у."),
    "hr": ("{sender} je podijelio izvještaj s vama",
           "{sender} je podijelio {report} s vama na BloomPrintu."),
    "tr": ("{sender} sizinle bir rapor paylaştı",
           "{sender} BloomPrint'te sizinle bir {report} paylaştı."),
    "ro": ("{sender} a partajat un raport cu tine",
           "{sender} a partajat un {report} cu tine pe BloomPrint."),
    "el": ("Ο/Η {sender} μοιράστηκε μια αναφορά μαζί σου",
           "Ο/Η {sender} μοιράστηκε ένα {report} μαζί σου στο BloomPrint."),
    "lt": ("{sender} pasidalijo su jumis ataskaita",
           "{sender} pasidalijo su jumis {report} BloomPrint sistemoje."),
    "ar": ("شارك {sender} تقريرًا معك",
           "شارك {sender} معك {report} على BloomPrint."),
    "he": ("{sender} שיתף איתך דוח",
           "{sender} שיתף איתך {report} ב־BloomPrint."),
    "hi": ("{sender} ने आपके साथ एक रिपोर्ट साझा की",
           "{sender} ने BloomPrint पर आपके साथ एक {report} साझा की है।"),
    "ka": ("{sender}-მა გაგიზიარათ ანგარიში",
           "{sender}-მა გაგიზიარათ {report} BloomPrint-ზე."),
    "ja": ("{sender} さんがレポートを共有しました",
           "{sender} さんが BloomPrint で {report} をあなたと共有しました。"),
    "ko": ("{sender}님이 리포트를 공유했습니다",
           "{sender}님이 BloomPrint에서 {report}을(를) 공유했습니다."),
    "zh": ("{sender} 与你分享了一份报告",
           "{sender} 在 BloomPrint 上与你分享了一份{report}。"),
    "tl": ("Nagbahagi si {sender} ng report sa iyo",
           "Nagbahagi si {sender} ng {report} sa iyo sa BloomPrint."),
}


EVENTS["report_request"] = {
    "en": ("{sender} requested a report",
           "{sender} asked you for a {report}."),
    "es": ("{sender} ha solicitado un informe",
           "{sender} te ha pedido un {report}."),
    "fr": ("{sender} a demandé un rapport",
           "{sender} vous a demandé un {report}."),
    "pt": ("{sender} solicitou um relatório",
           "{sender} pediu-lhe um {report}."),
    "it": ("{sender} ha richiesto un report",
           "{sender} ti ha chiesto un {report}."),
    "de": ("{sender} hat einen Bericht angefragt",
           "{sender} hat dich um einen {report} gebeten."),
    "nl": ("{sender} heeft een rapport aangevraagd",
           "{sender} heeft je om een {report} gevraagd."),
    "sv": ("{sender} har begärt en rapport",
           "{sender} har bett dig om en {report}."),
    "pl": ("{sender} poprosił o raport",
           "{sender} poprosił Cię o {report}."),
    "ru": ("{sender} запросил отчёт",
           "{sender} попросил у вас материал «{report}»."),
    "uk": ("{sender} запитав звіт",
           "{sender} попросив у вас матеріал «{report}»."),
    "sr": ("{sender} је затражио извештај",
           "{sender} је од вас затражио {report}."),
    "hr": ("{sender} je zatražio izvještaj",
           "{sender} je od vas zatražio {report}."),
    "tr": ("{sender} bir rapor istedi",
           "{sender} sizden bir {report} istedi."),
    "ro": ("{sender} a cerut un raport",
           "{sender} ți-a cerut un {report}."),
    "el": ("Ο/Η {sender} ζήτησε μια αναφορά",
           "Ο/Η {sender} σου ζήτησε ένα {report}."),
    "lt": ("{sender} paprašė ataskaitos",
           "{sender} paprašė jūsų {report}."),
    "ar": ("طلب {sender} تقريرًا",
           "طلب منك {sender} {report}."),
    "he": ("{sender} ביקש דוח",
           "{sender} ביקש ממך {report}."),
    "hi": ("{sender} ने एक रिपोर्ट माँगी",
           "{sender} ने आपसे एक {report} माँगी है।"),
    "ka": ("{sender}-მა მოითხოვა ანგარიში",
           "{sender}-მა მოგთხოვათ {report}."),
    "ja": ("{sender} さんがレポートを依頼しました",
           "{sender} さんがあなたに {report} を依頼しました。"),
    "ko": ("{sender}님이 리포트를 요청했습니다",
           "{sender}님이 {report}을(를) 요청했습니다."),
    "zh": ("{sender} 请求一份报告",
           "{sender} 向你请求一份{report}。"),
    "tl": ("Humiling si {sender} ng report",
           "Humiling sa iyo si {sender} ng {report}."),
}


EVENTS["report_declined"] = {
    "en": ("{sender} declined your report request",
           "{sender} declined your request for a {report}."),
    "es": ("{sender} ha rechazado tu solicitud de informe",
           "{sender} ha rechazado tu solicitud de un {report}."),
    "fr": ("{sender} a refusé votre demande de rapport",
           "{sender} a refusé votre demande de {report}."),
    "pt": ("{sender} recusou o seu pedido de relatório",
           "{sender} recusou o seu pedido de um {report}."),
    "it": ("{sender} ha rifiutato la tua richiesta",
           "{sender} ha rifiutato la tua richiesta di un {report}."),
    "de": ("{sender} hat deine Anfrage abgelehnt",
           "{sender} hat deine Anfrage für einen {report} abgelehnt."),
    "nl": ("{sender} heeft je aanvraag afgewezen",
           "{sender} heeft je aanvraag voor een {report} afgewezen."),
    "sv": ("{sender} avböjde din begäran",
           "{sender} avböjde din begäran om en {report}."),
    "pl": ("{sender} odrzucił Twoją prośbę",
           "{sender} odrzucił Twoją prośbę o {report}."),
    "ru": ("{sender} отклонил ваш запрос",
           "{sender} отклонил ваш запрос на материал «{report}»."),
    "uk": ("{sender} відхилив ваш запит",
           "{sender} відхилив ваш запит на матеріал «{report}»."),
    "sr": ("{sender} је одбио ваш захтев",
           "{sender} је одбио ваш захтев за {report}."),
    "hr": ("{sender} je odbio vaš zahtjev",
           "{sender} je odbio vaš zahtjev za {report}."),
    "tr": ("{sender} isteğinizi reddetti",
           "{sender} {report} isteğinizi reddetti."),
    "ro": ("{sender} ți-a respins cererea",
           "{sender} ți-a respins cererea pentru un {report}."),
    "el": ("Ο/Η {sender} απέρριψε το αίτημά σου",
           "Ο/Η {sender} απέρριψε το αίτημά σου για ένα {report}."),
    "lt": ("{sender} atmetė jūsų prašymą",
           "{sender} atmetė jūsų prašymą dėl {report}."),
    "ar": ("رفض {sender} طلبك",
           "رفض {sender} طلبك للحصول على {report}."),
    "he": ("{sender} דחה את בקשתך",
           "{sender} דחה את בקשתך ל{report}."),
    "hi": ("{sender} ने आपका अनुरोध अस्वीकार किया",
           "{sender} ने {report} के लिए आपका अनुरोध अस्वीकार कर दिया।"),
    "ka": ("{sender}-მა უარყო თქვენი მოთხოვნა",
           "{sender}-მა უარყო თქვენი მოთხოვნა {report}-ზე."),
    "ja": ("{sender} さんが依頼を辞退しました",
           "{sender} さんが {report} の依頼を辞退しました。"),
    "ko": ("{sender}님이 요청을 거절했습니다",
           "{sender}님이 {report} 요청을 거절했습니다."),
    "zh": ("{sender} 拒绝了你的请求",
           "{sender} 拒绝了你索取{report}的请求。"),
    "tl": ("Tinanggihan ni {sender} ang hiling mo",
           "Tinanggihan ni {sender} ang hiling mo para sa {report}."),
}


EVENTS["training_assigned"] = {
    "en": ("New training program: {title}",
           "{coach} assigned you a training program: {title}."),
    "es": ("Nuevo programa de entrenamiento: {title}",
           "{coach} te ha asignado un programa de entrenamiento: {title}."),
    "fr": ("Nouveau programme d'entraînement : {title}",
           "{coach} vous a attribué un programme d'entraînement : {title}."),
    "pt": ("Novo programa de treino: {title}",
           "{coach} atribuiu-lhe um programa de treino: {title}."),
    "it": ("Nuovo programma di allenamento: {title}",
           "{coach} ti ha assegnato un programma di allenamento: {title}."),
    "de": ("Neues Trainingsprogramm: {title}",
           "{coach} hat dir ein Trainingsprogramm zugewiesen: {title}."),
    "nl": ("Nieuw trainingsprogramma: {title}",
           "{coach} heeft je een trainingsprogramma toegewezen: {title}."),
    "sv": ("Nytt träningsprogram: {title}",
           "{coach} har tilldelat dig ett träningsprogram: {title}."),
    "pl": ("Nowy program treningowy: {title}",
           "{coach} przypisał Ci program treningowy: {title}."),
    "ru": ("Новая тренировочная программа: {title}",
           "{coach} назначил вам тренировочную программу: {title}."),
    "uk": ("Нова тренувальна програма: {title}",
           "{coach} призначив вам тренувальну програму: {title}."),
    "sr": ("Нови програм тренинга: {title}",
           "{coach} вам је доделио програм тренинга: {title}."),
    "hr": ("Novi program treninga: {title}",
           "{coach} vam je dodijelio program treninga: {title}."),
    "tr": ("Yeni antrenman programı: {title}",
           "{coach} size bir antrenman programı atadı: {title}."),
    "ro": ("Program nou de antrenament: {title}",
           "{coach} ți-a atribuit un program de antrenament: {title}."),
    "el": ("Νέο πρόγραμμα προπόνησης: {title}",
           "Ο/Η {coach} σου ανέθεσε ένα πρόγραμμα προπόνησης: {title}."),
    "lt": ("Nauja treniruočių programa: {title}",
           "{coach} priskyrė jums treniruočių programą: {title}."),
    "ar": ("برنامج تدريبي جديد: {title}",
           "أسند إليك {coach} برنامجًا تدريبيًا: {title}."),
    "he": ("תוכנית אימון חדשה: {title}",
           "{coach} הקצה לך תוכנית אימון: {title}."),
    "hi": ("नया प्रशिक्षण कार्यक्रम: {title}",
           "{coach} ने आपको एक प्रशिक्षण कार्यक्रम सौंपा है: {title}।"),
    "ka": ("ახალი სავარჯიშო პროგრამა: {title}",
           "{coach}-მა მოგანიჭათ სავარჯიშო პროგრამა: {title}."),
    "ja": ("新しいトレーニングプログラム: {title}",
           "{coach} さんがトレーニングプログラムを割り当てました: {title}。"),
    "ko": ("새 훈련 프로그램: {title}",
           "{coach}님이 훈련 프로그램을 배정했습니다: {title}."),
    "zh": ("新的训练计划：{title}",
           "{coach} 为你分配了一份训练计划：{title}。"),
    "tl": ("Bagong training program: {title}",
           "Binigyan ka ni {coach} ng training program: {title}."),
}


EVENTS["signup_coach"] = {
    "en": ("Welcome to BloomPrint",
           "BloomPrint writes player evaluations, scouting reports, game reports and training programs from your roster and the games you track.\n\nWhere to start.\n\n1. Fill in **System & Philosophy** on your profile. Describe your system and what you value in a player. The AI applies it to every report and every training program it writes, so the more you put in, the more closely the writing is framed around your system and how a player fits your team.\n\n2. Create a team and add your **roster**. Type players in one at a time, or upload any file and let the AI read it.\n\n3. Open a **player** and run an evaluation. The AI grades them against the six pillars, offense, defense, physical, intangibles, advanced and strategic fit, and gives you the reasoning behind every grade.\n\n4. Build a packet in **Team Eval/Packet**. Pull in film, the stats from a game you tracked and your scouting notes on the opponent, and the AI writes one report across all of it. Pick more than one report type and it combines them into a single document.\n\n**Ask BloomPrint** reads your own data to answer questions, and it assists you with the work:\n\n- Who are my top-graded players right now?\n- Which opponents did we struggle with?\n- Scout our next opponent\n- Build a coaching report for my team\n- How do I import a roster?"),
    "es": ("Bienvenido a BloomPrint",
           "Tu cuenta de entrenador está lista. Añade tu plantilla y podrás empezar a crear evaluaciones."),
    "fr": ("Bienvenue sur BloomPrint",
           "Votre compte entraîneur est prêt. Ajoutez votre effectif pour commencer à créer des évaluations."),
    "pt": ("Bem-vindo ao BloomPrint",
           "A sua conta de treinador está pronta. Adicione o seu plantel para começar a criar avaliações."),
    "it": ("Benvenuto su BloomPrint",
           "Il tuo account allenatore è pronto. Aggiungi la tua rosa per iniziare a creare valutazioni."),
    "de": ("Willkommen bei BloomPrint",
           "Dein Trainerkonto ist bereit. Füge deinen Kader hinzu, dann kannst du mit Bewertungen starten."),
    "nl": ("Welkom bij BloomPrint",
           "Je coachaccount is klaar. Voeg je selectie toe en je kunt beginnen met evaluaties."),
    "sv": ("Välkommen till BloomPrint",
           "Ditt tränarkonto är klart. Lägg till din trupp så kan du börja bygga utvärderingar."),
    "pl": ("Witamy w BloomPrint",
           "Twoje konto trenera jest gotowe. Dodaj skład, aby zacząć tworzyć oceny."),
    "ru": ("Добро пожаловать в BloomPrint",
           "Ваш аккаунт тренера готов. Добавьте состав, и можно приступать к оценкам."),
    "uk": ("Ласкаво просимо до BloomPrint",
           "Ваш обліковий запис тренера готовий. Додайте склад, і можна починати оцінювання."),
    "sr": ("Добро дошли у BloomPrint",
           "Ваш тренерски налог је спреман. Додајте свој тим и можете почети са проценама."),
    "hr": ("Dobrodošli u BloomPrint",
           "Vaš trenerski račun je spreman. Dodajte svoj sastav i možete početi s procjenama."),
    "tr": ("BloomPrint'e hoş geldiniz",
           "Antrenör hesabınız hazır. Kadronuzu ekleyin ve değerlendirmeler oluşturmaya başlayın."),
    "ro": ("Bine ai venit pe BloomPrint",
           "Contul tău de antrenor este gata. Adaugă lotul și poți începe să creezi evaluări."),
    "el": ("Καλώς ήρθες στο BloomPrint",
           "Ο λογαριασμός προπονητή σου είναι έτοιμος. Πρόσθεσε το ρόστερ σου και ξεκίνα αξιολογήσεις."),
    "lt": ("Sveiki atvykę į BloomPrint",
           "Jūsų trenerio paskyra paruošta. Pridėkite sudėtį ir galėsite kurti vertinimus."),
    "ar": ("مرحبًا بك في BloomPrint",
           "حساب المدرب الخاص بك جاهز. أضف قائمتك لتبدأ في إنشاء التقييمات."),
    "he": ("ברוך הבא ל־BloomPrint",
           "חשבון המאמן שלך מוכן. הוסף את הסגל שלך ותוכל להתחיל לבנות הערכות."),
    "hi": ("BloomPrint में आपका स्वागत है",
           "आपका कोच खाता तैयार है। अपनी रोस्टर जोड़ें और मूल्यांकन बनाना शुरू करें।"),
    "ka": ("კეთილი იყოს თქვენი მობრძანება BloomPrint-ზე",
           "თქვენი მწვრთნელის ანგარიში მზადაა. დაამატეთ შემადგენლობა და დაიწყეთ შეფასებები."),
    "ja": ("BloomPrint へようこそ",
           "コーチアカウントの準備ができました。ロスターを追加すると評価を作成できます。"),
    "ko": ("BloomPrint에 오신 것을 환영합니다",
           "코치 계정이 준비되었습니다. 로스터를 추가하면 평가를 만들 수 있습니다."),
    "zh": ("欢迎使用 BloomPrint",
           "你的教练账号已就绪。添加球员名单后即可开始创建评估。"),
    "tl": ("Maligayang pagdating sa BloomPrint",
           "Handa na ang coach account mo. Idagdag ang roster mo para makapagsimula ng mga evaluation."),
}


EVENTS["signup_player"] = {
    "en": ("Welcome to BloomPrint",
           "Your coaching staff can share reports and training programs with you here. Both are written by BloomPrint AI from your coach's own inputs and criteria, so what you read is measured against how they see the game.\n\nWhere to start.\n\n1. Link your account to your coach or trainer. They approve the request, and after that anything they send reaches you.\n\n2. A report arrives under **Reports** as soon as a coach or trainer sends you one. Open it to read what they wrote about you.\n\n3. Under **Training**, a program you have been sent is broken into a checklist by our AI. Tick items off as you go.\n\nComment on any report or program to ask a question, and your coach can answer in the same place."),
    "es": ("Bienvenido a BloomPrint",
           "Tu cuenta de jugador está lista. Vincúlala a tu equipo para ver tus evaluaciones y entrenamientos."),
    "fr": ("Bienvenue sur BloomPrint",
           "Votre compte joueur est prêt. Liez-le à votre équipe pour voir vos évaluations et entraînements."),
    "pt": ("Bem-vindo ao BloomPrint",
           "A sua conta de jogador está pronta. Associe-a à sua equipa para ver avaliações e treinos."),
    "it": ("Benvenuto su BloomPrint",
           "Il tuo account giocatore è pronto. Collegalo alla tua squadra per vedere valutazioni e allenamenti."),
    "de": ("Willkommen bei BloomPrint",
           "Dein Spielerkonto ist bereit. Verknüpfe es mit deinem Team, um Bewertungen und Training zu sehen."),
    "nl": ("Welkom bij BloomPrint",
           "Je spelersaccount is klaar. Koppel het aan je team om je evaluaties en trainingen te zien."),
    "sv": ("Välkommen till BloomPrint",
           "Ditt spelarkonto är klart. Koppla det till ditt lag för att se utvärderingar och träning."),
    "pl": ("Witamy w BloomPrint",
           "Twoje konto zawodnika jest gotowe. Połącz je z drużyną, aby zobaczyć oceny i treningi."),
    "ru": ("Добро пожаловать в BloomPrint",
           "Ваш аккаунт игрока готов. Привяжите его к команде, чтобы видеть оценки и тренировки."),
    "uk": ("Ласкаво просимо до BloomPrint",
           "Ваш обліковий запис гравця готовий. Прив'яжіть його до команди, щоб бачити оцінки й тренування."),
    "sr": ("Добро дошли у BloomPrint",
           "Ваш играчки налог је спреман. Повежите га са тимом да видите процене и тренинге."),
    "hr": ("Dobrodošli u BloomPrint",
           "Vaš igrački račun je spreman. Povežite ga s timom da vidite procjene i treninge."),
    "tr": ("BloomPrint'e hoş geldiniz",
           "Oyuncu hesabınız hazır. Değerlendirme ve antrenmanlarınızı görmek için takımınıza bağlayın."),
    "ro": ("Bine ai venit pe BloomPrint",
           "Contul tău de jucător este gata. Leagă-l de echipă ca să vezi evaluările și antrenamentele."),
    "el": ("Καλώς ήρθες στο BloomPrint",
           "Ο λογαριασμός παίκτη σου είναι έτοιμος. Σύνδεσέ τον με την ομάδα σου για αξιολογήσεις και προπονήσεις."),
    "lt": ("Sveiki atvykę į BloomPrint",
           "Jūsų žaidėjo paskyra paruošta. Susiekite ją su komanda, kad matytumėte vertinimus ir treniruotes."),
    "ar": ("مرحبًا بك في BloomPrint",
           "حساب اللاعب الخاص بك جاهز. اربطه بفريقك لعرض تقييماتك وبرامجك التدريبية."),
    "he": ("ברוך הבא ל־BloomPrint",
           "חשבון השחקן שלך מוכן. קשר אותו לקבוצה שלך כדי לראות הערכות ואימונים."),
    "hi": ("BloomPrint में आपका स्वागत है",
           "आपका खिलाड़ी खाता तैयार है। मूल्यांकन और प्रशिक्षण देखने के लिए इसे अपनी टीम से जोड़ें।"),
    "ka": ("კეთილი იყოს თქვენი მობრძანება BloomPrint-ზე",
           "თქვენი მოთამაშის ანგარიში მზადაა. დააკავშირეთ გუნდთან შეფასებებისა და ვარჯიშების სანახავად."),
    "ja": ("BloomPrint へようこそ",
           "選手アカウントの準備ができました。チームと連携すると評価とトレーニングを確認できます。"),
    "ko": ("BloomPrint에 오신 것을 환영합니다",
           "선수 계정이 준비되었습니다. 팀에 연결하면 평가와 훈련을 볼 수 있습니다."),
    "zh": ("欢迎使用 BloomPrint",
           "你的球员账号已就绪。关联你的球队后即可查看评估与训练。"),
    "tl": ("Maligayang pagdating sa BloomPrint",
           "Handa na ang player account mo. I-link ito sa team mo para makita ang evaluation at training mo."),
}


EVENTS["email_changed"] = {
    "en": ("Your BloomPrint email was changed",
           "The email on your account is now {email}. If this wasn't you, contact us straight away."),
    "es": ("Se ha cambiado tu correo de BloomPrint",
           "El correo de tu cuenta ahora es {email}. Si no has sido tú, contáctanos de inmediato."),
    "fr": ("Votre adresse e-mail BloomPrint a changé",
           "L'adresse de votre compte est désormais {email}. Si ce n'était pas vous, contactez-nous immédiatement."),
    "pt": ("O seu email do BloomPrint foi alterado",
           "O email da sua conta é agora {email}. Se não foi você, contacte-nos de imediato."),
    "it": ("La tua email BloomPrint è cambiata",
           "L'email del tuo account ora è {email}. Se non sei stato tu, contattaci subito."),
    "de": ("Deine BloomPrint-E-Mail wurde geändert",
           "Die E-Mail deines Kontos ist jetzt {email}. Falls du das nicht warst, melde dich sofort bei uns."),
    "nl": ("Je BloomPrint-e-mailadres is gewijzigd",
           "Het e-mailadres van je account is nu {email}. Was jij dit niet? Neem direct contact met ons op."),
    "sv": ("Din BloomPrint-e-post har ändrats",
           "E-postadressen på ditt konto är nu {email}. Om det inte var du, kontakta oss direkt."),
    "pl": ("Zmieniono Twój adres e-mail w BloomPrint",
           "Adres e-mail Twojego konta to teraz {email}. Jeśli to nie Ty, skontaktuj się z nami natychmiast."),
    "ru": ("Ваш адрес почты в BloomPrint изменён",
           "Адрес вашей учётной записи теперь {email}. Если это были не вы, немедленно свяжитесь с нами."),
    "uk": ("Вашу адресу пошти в BloomPrint змінено",
           "Адреса вашого облікового запису тепер {email}. Якщо це були не ви, негайно зв'яжіться з нами."),
    "sr": ("Ваша BloomPrint адреса је промењена",
           "Адреса вашег налога је сада {email}. Ако то нисте били ви, одмах нас контактирајте."),
    "hr": ("Vaša BloomPrint adresa je promijenjena",
           "Adresa vašeg računa sada je {email}. Ako to niste bili vi, odmah nas kontaktirajte."),
    "tr": ("BloomPrint e-posta adresiniz değişti",
           "Hesabınızın e-posta adresi artık {email}. Bunu siz yapmadıysanız hemen bizimle iletişime geçin."),
    "ro": ("Adresa ta de email BloomPrint a fost schimbată",
           "Emailul contului tău este acum {email}. Dacă nu ai fost tu, contactează-ne imediat."),
    "el": ("Το email σου στο BloomPrint άλλαξε",
           "Το email του λογαριασμού σου είναι πλέον {email}. Αν δεν το έκανες εσύ, επικοινώνησε αμέσως μαζί μας."),
    "lt": ("Jūsų BloomPrint el. paštas pakeistas",
           "Jūsų paskyros el. paštas dabar yra {email}. Jei tai buvote ne jūs, nedelsdami susisiekite su mumis."),
    "ar": ("تم تغيير بريدك في BloomPrint",
           "بريد حسابك الآن هو {email}. إذا لم تكن أنت من قام بذلك، تواصل معنا فورًا."),
    "he": ("כתובת המייל שלך ב־BloomPrint שונתה",
           "כתובת המייל בחשבון שלך היא כעת {email}. אם זה לא היית אתה, צור איתנו קשר מיד."),
    "hi": ("आपका BloomPrint ईमेल बदल दिया गया",
           "आपके खाते का ईमेल अब {email} है। यदि यह आपने नहीं किया, तो तुरंत हमसे संपर्क करें।"),
    "ka": ("თქვენი BloomPrint-ის ელფოსტა შეიცვალა",
           "თქვენი ანგარიშის ელფოსტა ახლა არის {email}. თუ ეს თქვენ არ ყოფილხართ, დაუყოვნებლივ დაგვიკავშირდით."),
    "ja": ("BloomPrint のメールアドレスが変更されました",
           "アカウントのメールアドレスが {email} になりました。心当たりがない場合はすぐにご連絡ください。"),
    "ko": ("BloomPrint 이메일이 변경되었습니다",
           "계정 이메일이 {email}(으)로 변경되었습니다. 본인이 아니라면 즉시 문의해 주세요."),
    "zh": ("你的 BloomPrint 邮箱已更改",
           "你账号的邮箱现已改为 {email}。如果这不是你本人操作，请立即联系我们。"),
    "tl": ("Nabago ang BloomPrint email mo",
           "Ang email ng account mo ay {email} na. Kung hindi ikaw ang gumawa nito, agad kaming kontakin."),
}


EVENTS["password_reset"] = {
    "en": ('Reset your BloomPrint password',
           'Use the link below to choose a new password. It works once and expires in 24 hours. If you did not ask for this, nothing has changed and you can ignore this message.'),
    "es": ('Restablece tu contraseña de BloomPrint',
           'Usa el enlace de abajo para elegir una nueva contraseña. Funciona una sola vez y caduca en 24 horas. Si no lo has solicitado, no ha cambiado nada y puedes ignorar este mensaje.'),
    "fr": ('Réinitialisez votre mot de passe BloomPrint',
           "Utilisez le lien ci-dessous pour choisir un nouveau mot de passe. Il fonctionne une seule fois et expire dans 24 heures. Si vous n'êtes pas à l'origine de cette demande, rien n'a changé et vous pouvez ignorer ce message."),
    "pt": ('Redefina a sua palavra-passe do BloomPrint',
           'Use a ligação abaixo para escolher uma nova palavra-passe. Funciona uma vez e expira em 24 horas. Se não pediu isto, nada mudou e pode ignorar esta mensagem.'),
    "it": ('Reimposta la tua password BloomPrint',
           'Usa il link qui sotto per scegliere una nuova password. Funziona una volta sola e scade tra 24 ore. Se non hai richiesto tu questa operazione, nulla è cambiato e puoi ignorare questo messaggio.'),
    "de": ('Setze dein BloomPrint-Passwort zurück',
           'Über den Link unten kannst du ein neues Passwort wählen. Er funktioniert einmal und läuft in 24 Stunden ab. Wenn du das nicht angefordert hast, hat sich nichts geändert und du kannst diese Nachricht ignorieren.'),
    "nl": ('Stel je BloomPrint-wachtwoord opnieuw in',
           'Gebruik de link hieronder om een nieuw wachtwoord te kiezen. Hij werkt één keer en verloopt over 24 uur. Heb je dit niet aangevraagd, dan is er niets veranderd en kun je dit bericht negeren.'),
    "sv": ('Återställ ditt BloomPrint-lösenord',
           'Använd länken nedan för att välja ett nytt lösenord. Den fungerar en gång och slutar gälla om 24 timmar. Om du inte har begärt detta har ingenting ändrats och du kan bortse från meddelandet.'),
    "pl": ('Zresetuj hasło do BloomPrint',
           'Skorzystaj z poniższego linku, aby ustawić nowe hasło. Działa jeden raz i wygasa po 24 godzinach. Jeśli to nie Ty prosiłeś o zmianę, nic się nie zmieniło i możesz zignorować tę wiadomość.'),
    "ru": ('Сброс пароля BloomPrint',
           'Перейдите по ссылке ниже, чтобы задать новый пароль. Она сработает один раз и истечёт через 24 часа. Если вы этого не запрашивали, ничего не изменилось и письмо можно не читать.'),
    "uk": ('Скидання пароля BloomPrint',
           'Скористайтеся посиланням нижче, щоб задати новий пароль. Воно спрацює один раз і діє 24 години. Якщо ви цього не запитували, нічого не змінилося і лист можна проігнорувати.'),
    "sr": ('Ресетујте лозинку за BloomPrint',
           'Употребите везу испод да изаберете нову лозинку. Ради једном и истиче за 24 сата. Ако то нисте тражили, ништа се није променило и можете занемарити ову поруку.'),
    "hr": ('Poništite svoju BloomPrint lozinku',
           'Upotrijebite poveznicu ispod za odabir nove lozinke. Radi jednom i istječe za 24 sata. Ako to niste tražili, ništa se nije promijenilo i možete zanemariti ovu poruku.'),
    "tr": ('BloomPrint şifrenizi sıfırlayın',
           'Yeni bir şifre seçmek için aşağıdaki bağlantıyı kullanın. Bir kez çalışır ve 24 saat içinde geçerliliğini yitirir. Bunu siz istemediyseniz hiçbir şey değişmedi, bu mesajı yok sayabilirsiniz.'),
    "ro": ('Resetează-ți parola BloomPrint',
           'Folosește linkul de mai jos pentru a alege o parolă nouă. Funcționează o singură dată și expiră în 24 de ore. Dacă nu tu ai cerut asta, nu s-a schimbat nimic și poți ignora mesajul.'),
    "el": ('Επαναφορά του κωδικού σας στο BloomPrint',
           'Χρησιμοποιήστε τον παρακάτω σύνδεσμο για να επιλέξετε νέο κωδικό. Λειτουργεί μία φορά και λήγει σε 24 ώρες. Αν δεν το ζητήσατε εσείς, δεν άλλαξε τίποτα και μπορείτε να αγνοήσετε το μήνυμα.'),
    "lt": ('Atkurkite BloomPrint slaptažodį',
           'Nauju slaptažodžiu pasirinkti naudokite žemiau esančią nuorodą. Ji veikia vieną kartą ir nustoja galioti po 24 valandų. Jei to neprašėte, niekas nepasikeitė ir žinutę galite ignoruoti.'),
    "ar": ('إعادة تعيين كلمة مرور BloomPrint',
           'استخدم الرابط أدناه لاختيار كلمة مرور جديدة. يعمل مرة واحدة وتنتهي صلاحيته خلال ٢٤ ساعة. إذا لم تطلب ذلك، فلم يتغير شيء ويمكنك تجاهل هذه الرسالة.'),
    "he": ('איפוס הסיסמה שלך ב-BloomPrint',
           'השתמשו בקישור שלמטה כדי לבחור סיסמה חדשה. הוא פועל פעם אחת ופג תוך 24 שעות. אם לא ביקשתם זאת, שום דבר לא השתנה ואפשר להתעלם מההודעה.'),
    "hi": ('अपना BloomPrint पासवर्ड रीसेट करें',
           'नया पासवर्ड चुनने के लिए नीचे दिए गए लिंक का उपयोग करें। यह एक बार काम करता है और 24 घंटे में समाप्त हो जाता है। यदि आपने यह अनुरोध नहीं किया, तो कुछ नहीं बदला है और आप इस संदेश को अनदेखा कर सकते हैं।'),
    "ka": ('აღადგინეთ BloomPrint-ის პაროლი',
           'ახალი პაროლის ასარჩევად გამოიყენეთ ქვემოთ მოცემული ბმული. ის ერთხელ მუშაობს და 24 საათში იწურება. თუ ეს თქვენ არ მოგითხოვიათ, არაფერი შეცვლილა და შეგიძლიათ უგულებელყოთ ეს წერილი.'),
    "ja": ('BloomPrint のパスワードを再設定',
           '下のリンクから新しいパスワードを設定してください。リンクは一度だけ有効で、24時間で期限が切れます。心当たりがない場合、何も変更されていませんのでこのメールは無視してください。'),
    "ko": ('BloomPrint 비밀번호 재설정',
           '아래 링크에서 새 비밀번호를 설정하세요. 링크는 한 번만 사용할 수 있으며 24시간 후 만료됩니다. 요청하지 않으셨다면 변경된 것은 없으니 이 메일은 무시하셔도 됩니다.'),
    "zh": ('重置你的 BloomPrint 密码',
           '使用下方链接设置新密码。该链接仅可使用一次，24 小时后失效。如果这不是你发起的，账户没有任何变化，可以忽略此邮件。'),
    "tl": ('I-reset ang iyong BloomPrint password',
           'Gamitin ang link sa ibaba para pumili ng bagong password. Isang beses itong gumagana at mag-e-expire sa loob ng 24 na oras. Kung hindi ikaw ang humiling nito, walang nagbago at pwede mong balewalain ang mensaheng ito.'),
}

EVENTS["password_changed"] = {
    "en": ('Your BloomPrint password was changed',
           "The password on your account has been changed and every other device has been signed out. If this wasn't you, write to us straight away."),
    "es": ('Se ha cambiado tu contraseña de BloomPrint',
           'La contraseña de tu cuenta se ha cambiado y se ha cerrado la sesión en los demás dispositivos. Si no has sido tú, escríbenos de inmediato.'),
    "fr": ('Votre mot de passe BloomPrint a été modifié',
           "Le mot de passe de votre compte a été modifié et tous les autres appareils ont été déconnectés. Si ce n'était pas vous, écrivez-nous immédiatement."),
    "pt": ('A sua palavra-passe do BloomPrint foi alterada',
           'A palavra-passe da sua conta foi alterada e a sessão foi terminada em todos os outros dispositivos. Se não foi você, escreva-nos de imediato.'),
    "it": ('La tua password BloomPrint è stata modificata',
           'La password del tuo account è stata modificata e tutti gli altri dispositivi sono stati disconnessi. Se non sei stato tu, scrivici subito.'),
    "de": ('Dein BloomPrint-Passwort wurde geändert',
           'Das Passwort deines Kontos wurde geändert und alle anderen Geräte wurden abgemeldet. Wenn du das nicht warst, schreib uns sofort.'),
    "nl": ('Je BloomPrint-wachtwoord is gewijzigd',
           'Het wachtwoord van je account is gewijzigd en alle andere apparaten zijn afgemeld. Was jij dit niet, mail ons dan meteen.'),
    "sv": ('Ditt BloomPrint-lösenord har ändrats',
           'Lösenordet för ditt konto har ändrats och alla andra enheter har loggats ut. Om det inte var du, hör av dig direkt.'),
    "pl": ('Hasło do BloomPrint zostało zmienione',
           'Hasło do Twojego konta zostało zmienione, a pozostałe urządzenia zostały wylogowane. Jeśli to nie Ty, napisz do nas natychmiast.'),
    "ru": ('Пароль BloomPrint изменён',
           'Пароль вашей учётной записи изменён, на всех других устройствах выполнен выход. Если это были не вы, напишите нам немедленно.'),
    "uk": ('Пароль BloomPrint змінено',
           'Пароль вашого облікового запису змінено, на всіх інших пристроях виконано вихід. Якщо це були не ви, напишіть нам негайно.'),
    "sr": ('Ваша BloomPrint лозинка је промењена',
           'Лозинка вашег налога је промењена и одјављени сте са свих других уређаја. Ако то нисте били ви, пишите нам одмах.'),
    "hr": ('Vaša BloomPrint lozinka je promijenjena',
           'Lozinka vašeg računa je promijenjena i odjavljeni ste sa svih drugih uređaja. Ako to niste bili vi, pišite nam odmah.'),
    "tr": ('BloomPrint şifreniz değiştirildi',
           'Hesabınızın şifresi değiştirildi ve diğer tüm cihazlardaki oturumlar kapatıldı. Bunu siz yapmadıysanız hemen bize yazın.'),
    "ro": ('Parola ta BloomPrint a fost schimbată',
           'Parola contului tău a fost schimbată și toate celelalte dispozitive au fost deconectate. Dacă nu ai fost tu, scrie-ne imediat.'),
    "el": ('Ο κωδικός σας στο BloomPrint άλλαξε',
           'Ο κωδικός του λογαριασμού σας άλλαξε και έγινε αποσύνδεση από κάθε άλλη συσκευή. Αν δεν το κάνατε εσείς, γράψτε μας αμέσως.'),
    "lt": ('Jūsų BloomPrint slaptažodis pakeistas',
           'Jūsų paskyros slaptažodis pakeistas, o visi kiti įrenginiai atjungti. Jei tai buvote ne jūs, parašykite mums nedelsdami.'),
    "ar": ('تم تغيير كلمة مرور BloomPrint',
           'تم تغيير كلمة مرور حسابك وتسجيل الخروج من جميع الأجهزة الأخرى. إذا لم تكن أنت، فراسلنا فورًا.'),
    "he": ('הסיסמה שלך ב-BloomPrint שונתה',
           'הסיסמה לחשבון שלך שונתה וכל שאר המכשירים נותקו. אם זה לא היה אתם, כתבו לנו מיד.'),
    "hi": ('आपका BloomPrint पासवर्ड बदल दिया गया',
           'आपके खाते का पासवर्ड बदल दिया गया है और बाकी सभी डिवाइस से साइन आउट कर दिया गया है। यदि यह आपने नहीं किया, तो हमें तुरंत लिखें।'),
    "ka": ('თქვენი BloomPrint-ის პაროლი შეიცვალა',
           'თქვენი ანგარიშის პაროლი შეიცვალა და ყველა სხვა მოწყობილობიდან სისტემიდან გამოხვედით. თუ ეს თქვენ არ იყავით, მოგვწერეთ დაუყოვნებლივ.'),
    "ja": ('BloomPrint のパスワードが変更されました',
           'アカウントのパスワードが変更され、他のすべての端末からサインアウトされました。心当たりがない場合はすぐにご連絡ください。'),
    "ko": ('BloomPrint 비밀번호가 변경되었습니다',
           '계정 비밀번호가 변경되었고 다른 모든 기기에서 로그아웃되었습니다. 본인이 아니라면 즉시 연락해 주세요.'),
    "zh": ('你的 BloomPrint 密码已更改',
           '你的账户密码已更改，其他所有设备均已退出登录。如果这不是你操作的，请立即联系我们。'),
    "tl": ('Nabago ang iyong BloomPrint password',
           'Nabago ang password ng iyong account at na-sign out na ang lahat ng ibang device. Kung hindi ikaw ang gumawa nito, sulatan mo kami agad.'),
}