"""Subject and body for each event, per language.

One short sentence each. The greeting, the link and the footer come from the
shell in emails.py, so nothing here repeats what every message already says.

Placeholders are filled from the same params the in-app notification carries,
so a notification and its email cannot describe the event differently.
"""

# event -> lang -> (subject, body)
EVENTS: dict[str, dict[str, tuple[str, str]]] = {}


EVENTS["staff_invite"] = {
    "en": ("{inviter} invited you to {team}",
           "{inviter} invited you to join the staff of {team} on BloomPrint."),
    "es": ("{inviter} te ha invitado a {team}",
           "{inviter} te ha invitado a formar parte del cuerpo técnico de {team} en BloomPrint."),
    "fr": ("{inviter} vous a invité à rejoindre {team}",
           "{inviter} vous a invité à rejoindre le staff de {team} sur BloomPrint."),
    "pt": ("{inviter} convidou-o para {team}",
           "{inviter} convidou-o para integrar a equipa técnica de {team} no BloomPrint."),
    "it": ("{inviter} ti ha invitato in {team}",
           "{inviter} ti ha invitato a entrare nello staff di {team} su BloomPrint."),
    "de": ("{inviter} hat dich zu {team} eingeladen",
           "{inviter} hat dich eingeladen, dem Trainerstab von {team} auf BloomPrint beizutreten."),
    "nl": ("{inviter} heeft je uitgenodigd voor {team}",
           "{inviter} heeft je uitgenodigd om deel uit te maken van de staf van {team} op BloomPrint."),
    "sv": ("{inviter} har bjudit in dig till {team}",
           "{inviter} har bjudit in dig till ledarstaben för {team} på BloomPrint."),
    "pl": ("{inviter} zaprosił Cię do {team}",
           "{inviter} zaprosił Cię do sztabu {team} w BloomPrint."),
    "ru": ("{inviter} приглашает вас в {team}",
           "{inviter} приглашает вас войти в тренерский штаб команды {team} в BloomPrint."),
    "uk": ("{inviter} запрошує вас до {team}",
           "{inviter} запрошує вас увійти до тренерського штабу команди {team} у BloomPrint."),
    "sr": ("{inviter} вас позива у {team}",
           "{inviter} вас позива да се придружите стручном штабу тима {team} на BloomPrint-у."),
    "hr": ("{inviter} vas poziva u {team}",
           "{inviter} vas poziva da se pridružite stručnom stožeru tima {team} na BloomPrintu."),
    "tr": ("{inviter} sizi {team} takımına davet etti",
           "{inviter} sizi BloomPrint'te {team} teknik ekibine katılmaya davet etti."),
    "ro": ("{inviter} te-a invitat la {team}",
           "{inviter} te-a invitat să faci parte din staff-ul echipei {team} pe BloomPrint."),
    "el": ("Ο/Η {inviter} σε προσκάλεσε στην {team}",
           "Ο/Η {inviter} σε προσκάλεσε να μπεις στο προπονητικό τιμ της {team} στο BloomPrint."),
    "lt": ("{inviter} pakvietė jus į {team}",
           "{inviter} pakvietė jus prisijungti prie {team} trenerių štabo BloomPrint sistemoje."),
    "ar": ("دعاك {inviter} للانضمام إلى {team}",
           "دعاك {inviter} للانضمام إلى الجهاز الفني لفريق {team} على BloomPrint."),
    "he": ("{inviter} הזמין אותך ל־{team}",
           "{inviter} הזמין אותך להצטרף לצוות המקצועי של {team} ב־BloomPrint."),
    "hi": ("{inviter} ने आपको {team} में आमंत्रित किया",
           "{inviter} ने आपको BloomPrint पर {team} के कोचिंग स्टाफ़ में शामिल होने के लिए आमंत्रित किया है।"),
    "ka": ("{inviter}-მა მოგიწვიათ {team}-ში",
           "{inviter}-მა მოგიწვიათ {team}-ის სამწვრთნელო შტაბში BloomPrint-ზე."),
    "ja": ("{inviter} さんが {team} に招待しました",
           "{inviter} さんが BloomPrint の {team} のスタッフとしてあなたを招待しました。"),
    "ko": ("{inviter}님이 {team}에 초대했습니다",
           "{inviter}님이 BloomPrint에서 {team} 코칭 스태프로 초대했습니다."),
    "zh": ("{inviter} 邀请你加入 {team}",
           "{inviter} 邀请你加入 BloomPrint 上 {team} 的教练组。"),
    "tl": ("Inimbitahan ka ni {inviter} sa {team}",
           "Inimbitahan ka ni {inviter} na sumali sa staff ng {team} sa BloomPrint."),
}


EVENTS["team_join_request"] = {
    "en": ("{coach} asked to join {team}",
           "{coach} has asked to join {team}. You can approve or decline the request."),
    "es": ("{coach} ha pedido unirse a {team}",
           "{coach} ha pedido unirse a {team}. Puedes aceptar o rechazar la solicitud."),
    "fr": ("{coach} demande à rejoindre {team}",
           "{coach} demande à rejoindre {team}. Vous pouvez accepter ou refuser la demande."),
    "pt": ("{coach} pediu para entrar em {team}",
           "{coach} pediu para entrar em {team}. Pode aceitar ou recusar o pedido."),
    "it": ("{coach} ha chiesto di entrare in {team}",
           "{coach} ha chiesto di entrare in {team}. Puoi accettare o rifiutare la richiesta."),
    "de": ("{coach} möchte {team} beitreten",
           "{coach} möchte {team} beitreten. Du kannst die Anfrage annehmen oder ablehnen."),
    "nl": ("{coach} wil zich aansluiten bij {team}",
           "{coach} wil zich aansluiten bij {team}. Je kunt het verzoek goedkeuren of afwijzen."),
    "sv": ("{coach} vill gå med i {team}",
           "{coach} vill gå med i {team}. Du kan godkänna eller avslå förfrågan."),
    "pl": ("{coach} prosi o dołączenie do {team}",
           "{coach} prosi o dołączenie do {team}. Możesz zaakceptować lub odrzucić prośbę."),
    "ru": ("{coach} просит принять в {team}",
           "{coach} просит принять его в команду {team}. Вы можете одобрить или отклонить запрос."),
    "uk": ("{coach} просить прийняти до {team}",
           "{coach} просить прийняти його до команди {team}. Ви можете схвалити або відхилити запит."),
    "sr": ("{coach} тражи да се придружи тиму {team}",
           "{coach} тражи да се придружи тиму {team}. Можете одобрити или одбити захтев."),
    "hr": ("{coach} traži pridruživanje timu {team}",
           "{coach} traži pridruživanje timu {team}. Možete odobriti ili odbiti zahtjev."),
    "tr": ("{coach} {team} takımına katılmak istiyor",
           "{coach} {team} takımına katılmak istiyor. İsteği onaylayabilir veya reddedebilirsiniz."),
    "ro": ("{coach} cere să se alăture echipei {team}",
           "{coach} cere să se alăture echipei {team}. Poți aproba sau respinge cererea."),
    "el": ("Ο/Η {coach} ζήτησε να μπει στην {team}",
           "Ο/Η {coach} ζήτησε να μπει στην {team}. Μπορείς να εγκρίνεις ή να απορρίψεις το αίτημα."),
    "lt": ("{coach} prašo prisijungti prie {team}",
           "{coach} prašo prisijungti prie {team}. Galite patvirtinti arba atmesti prašymą."),
    "ar": ("طلب {coach} الانضمام إلى {team}",
           "طلب {coach} الانضمام إلى {team}. يمكنك قبول الطلب أو رفضه."),
    "he": ("{coach} ביקש להצטרף ל־{team}",
           "{coach} ביקש להצטרף ל־{team}. אפשר לאשר או לדחות את הבקשה."),
    "hi": ("{coach} ने {team} में शामिल होने का अनुरोध किया",
           "{coach} ने {team} में शामिल होने का अनुरोध किया है। आप इसे स्वीकार या अस्वीकार कर सकते हैं।"),
    "ka": ("{coach} ითხოვს {team}-ში გაწევრიანებას",
           "{coach} ითხოვს {team}-ში გაწევრიანებას. შეგიძლიათ დაადასტუროთ ან უარყოთ მოთხოვნა."),
    "ja": ("{coach} さんが {team} への参加を希望しています",
           "{coach} さんが {team} への参加を希望しています。承認または却下できます。"),
    "ko": ("{coach}님이 {team} 합류를 요청했습니다",
           "{coach}님이 {team} 합류를 요청했습니다. 요청을 승인하거나 거절할 수 있습니다."),
    "zh": ("{coach} 申请加入 {team}",
           "{coach} 申请加入 {team}。你可以批准或拒绝该申请。"),
    "tl": ("Humiling si {coach} na sumali sa {team}",
           "Humiling si {coach} na sumali sa {team}. Maaari mong aprubahan o tanggihan ang hiling."),
}


EVENTS["team_join_approved"] = {
    "en": ("You're now staff on {team}",
           "Your request to join {team} was approved. You now have access to the team."),
    "es": ('Ya formas parte del cuerpo técnico de {team}',
           "Tu solicitud para unirte a {team} ha sido aceptada. Ya tienes acceso al equipo."),
    "fr": ('Vous faites maintenant partie du staff de {team}',
           "Votre demande pour rejoindre {team} a été acceptée. Vous avez désormais accès à l'équipe."),
    "pt": ('Já faz parte da equipa técnica de {team}',
           "O seu pedido para entrar em {team} foi aceite. Já tem acesso à equipa."),
    "it": ('Ora fai parte dello staff di {team}',
           "La tua richiesta di entrare in {team} è stata accettata. Ora hai accesso alla squadra."),
    "de": ('Du gehörst jetzt zum Staff von {team}',
           "Deine Anfrage für {team} wurde angenommen. Du hast jetzt Zugriff auf das Team."),
    "nl": ('Je hoort nu bij de staf van {team}',
           "Je verzoek om je aan te sluiten bij {team} is goedgekeurd. Je hebt nu toegang tot het team."),
    "sv": ('Du ingår nu i staben för {team}',
           "Din förfrågan om att gå med i {team} har godkänts. Du har nu tillgång till laget."),
    "pl": ('Należysz teraz do sztabu {team}',
           "Twoja prośba o dołączenie do {team} została zaakceptowana. Masz teraz dostęp do zespołu."),
    "ru": ('Теперь вы в тренерском штабе {team}',
           "Ваш запрос на вступление в {team} одобрен. Теперь у вас есть доступ к команде."),
    "uk": ('Тепер ви в тренерському штабі {team}',
           "Ваш запит на приєднання до {team} схвалено. Тепер ви маєте доступ до команди."),
    "sr": ('Сада сте у стручном штабу {team}',
           "Ваш захтев за придруживање тиму {team} је одобрен. Сада имате приступ тиму."),
    "hr": ('Sada ste u stručnom stožeru {team}',
           "Vaš zahtjev za pridruživanje timu {team} je odobren. Sada imate pristup timu."),
    "tr": ('Artık {team} teknik ekibindesiniz',
           "{team} takımına katılma isteğiniz onaylandı. Artık takıma erişebilirsiniz."),
    "ro": ('Acum faci parte din staff-ul {team}',
           "Cererea ta de a te alătura echipei {team} a fost aprobată. Ai acum acces la echipă."),
    "el": ('Ανήκεις πλέον στο επιτελείο της {team}',
           "Το αίτημά σου να μπεις στην {team} εγκρίθηκε. Έχεις πλέον πρόσβαση στην ομάδα."),
    "lt": ('Dabar esate {team} trenerių štabe',
           "Jūsų prašymas prisijungti prie {team} patvirtintas. Dabar turite prieigą prie komandos."),
    "ar": ('أصبحت الآن ضمن الطاقم الفني لـ {team}',
           "تمت الموافقة على طلبك للانضمام إلى {team}. أصبح لديك الآن حق الوصول إلى الفريق."),
    "he": ('אתה נמנה כעת עם הצוות של {team}',
           "הבקשה שלך להצטרף ל־{team} אושרה. יש לך כעת גישה לקבוצה."),
    "hi": ('अब आप {team} के स्टाफ में हैं',
           "{team} में शामिल होने का आपका अनुरोध स्वीकार कर लिया गया है। अब आपके पास टीम की पहुँच है।"),
    "ka": ('ახლა თქვენ ხართ {team}-ის შტაბში',
           "თქვენი მოთხოვნა {team}-ში გაწევრიანებაზე დამტკიცდა. ახლა გაქვთ წვდომა გუნდზე."),
    "ja": ('{team} のスタッフになりました',
           "{team} への参加リクエストが承認されました。チームにアクセスできます。"),
    "ko": ('이제 {team} 스태프입니다',
           "{team} 합류 요청이 승인되었습니다. 이제 팀에 접근할 수 있습니다."),
    "zh": ('你现在是 {team} 的教练组成员',
           "你加入 {team} 的申请已通过。现在你可以访问该球队了。"),
    "tl": ('Kabilang ka na sa staff ng {team}',
           "Naaprubahan ang hiling mong sumali sa {team}. May access ka na sa koponan."),
}


EVENTS["team_join_rejected"] = {
    "en": ("Your request to join {team}",
           "Your request to join {team} wasn't approved this time."),
    "es": ("Tu solicitud para unirte a {team}",
           "Tu solicitud para unirte a {team} no ha sido aceptada esta vez."),
    "fr": ("Votre demande pour rejoindre {team}",
           "Votre demande pour rejoindre {team} n'a pas été acceptée cette fois."),
    "pt": ("O seu pedido para entrar em {team}",
           "O seu pedido para entrar em {team} não foi aceite desta vez."),
    "it": ("La tua richiesta di entrare in {team}",
           "La tua richiesta di entrare in {team} non è stata accettata questa volta."),
    "de": ("Deine Anfrage für {team}",
           "Deine Anfrage für {team} wurde diesmal nicht angenommen."),
    "nl": ("Je verzoek voor {team}",
           "Je verzoek om je aan te sluiten bij {team} is deze keer niet goedgekeurd."),
    "sv": ("Din förfrågan om {team}",
           "Din förfrågan om att gå med i {team} godkändes inte den här gången."),
    "pl": ("Twoja prośba o dołączenie do {team}",
           "Twoja prośba o dołączenie do {team} nie została tym razem zaakceptowana."),
    "ru": ("Ваш запрос в {team}",
           "Ваш запрос на вступление в {team} на этот раз не был одобрен."),
    "uk": ("Ваш запит до {team}",
           "Ваш запит на приєднання до {team} цього разу не було схвалено."),
    "sr": ("Ваш захтев за {team}",
           "Ваш захтев за придруживање тиму {team} овог пута није одобрен."),
    "hr": ("Vaš zahtjev za {team}",
           "Vaš zahtjev za pridruživanje timu {team} ovaj put nije odobren."),
    "tr": ("{team} için isteğiniz",
           "{team} takımına katılma isteğiniz bu kez onaylanmadı."),
    "ro": ("Cererea ta pentru {team}",
           "Cererea ta de a te alătura echipei {team} nu a fost aprobată de această dată."),
    "el": ("Το αίτημά σου για την {team}",
           "Το αίτημά σου να μπεις στην {team} δεν εγκρίθηκε αυτή τη φορά."),
    "lt": ("Jūsų prašymas dėl {team}",
           "Jūsų prašymas prisijungti prie {team} šįkart nebuvo patvirtintas."),
    "ar": ("طلبك للانضمام إلى {team}",
           "لم تتم الموافقة على طلبك للانضمام إلى {team} هذه المرة."),
    "he": ("הבקשה שלך להצטרף ל־{team}",
           "הבקשה שלך להצטרף ל־{team} לא אושרה הפעם."),
    "hi": ("{team} में शामिल होने का आपका अनुरोध",
           "{team} में शामिल होने का आपका अनुरोध इस बार स्वीकार नहीं किया गया।"),
    "ka": ("თქვენი მოთხოვნა {team}-ზე",
           "თქვენი მოთხოვნა {team}-ში გაწევრიანებაზე ამჯერად არ დამტკიცდა."),
    "ja": ("{team} への参加リクエストについて",
           "{team} への参加リクエストは今回は承認されませんでした。"),
    "ko": ("{team} 합류 요청 안내",
           "{team} 합류 요청이 이번에는 승인되지 않았습니다."),
    "zh": ("你加入 {team} 的申请",
           "你加入 {team} 的申请这次未获通过。"),
    "tl": ("Ang hiling mong sumali sa {team}",
           "Hindi naaprubahan sa pagkakataong ito ang hiling mong sumali sa {team}."),
}


EVENTS["player_link_request"] = {
    "en": ("{player} wants to link to your roster",
           "{player} has asked to link their account to a player on your roster."),
    "es": ("{player} quiere vincularse a tu plantilla",
           "{player} ha pedido vincular su cuenta a un jugador de tu plantilla."),
    "fr": ("{player} souhaite se lier à votre effectif",
           "{player} a demandé à lier son compte à un joueur de votre effectif."),
    "pt": ("{player} quer associar-se ao seu plantel",
           "{player} pediu para associar a sua conta a um jogador do seu plantel."),
    "it": ("{player} vuole collegarsi alla tua rosa",
           "{player} ha chiesto di collegare il proprio account a un giocatore della tua rosa."),
    "de": ("{player} möchte sich mit deinem Kader verknüpfen",
           "{player} möchte das eigene Konto mit einem Spieler in deinem Kader verknüpfen."),
    "nl": ("{player} wil koppelen aan je selectie",
           "{player} heeft gevraagd om het account te koppelen aan een speler in je selectie."),
    "sv": ("{player} vill kopplas till din trupp",
           "{player} har bett om att koppla sitt konto till en spelare i din trupp."),
    "pl": ("{player} chce połączyć się z Twoim składem",
           "{player} poprosił o połączenie swojego konta z zawodnikiem z Twojego składu."),
    "ru": ("{player} хочет привязаться к вашему составу",
           "{player} просит привязать свою учётную запись к игроку из вашего состава."),
    "uk": ("{player} хоче прив'язатися до вашого складу",
           "{player} просить прив'язати свій обліковий запис до гравця з вашого складу."),
    "sr": ("{player} жели да се повеже са вашим тимом",
           "{player} тражи да повеже свој налог са играчем из вашег тима."),
    "hr": ("{player} se želi povezati s vašim sastavom",
           "{player} traži povezivanje svojeg računa s igračem iz vašeg sastava."),
    "tr": ("{player} kadronuza bağlanmak istiyor",
           "{player} hesabını kadronuzdaki bir oyuncuya bağlamak istiyor."),
    "ro": ("{player} vrea să se lege de lotul tău",
           "{player} a cerut să își lege contul de un jucător din lotul tău."),
    "el": ("Ο/Η {player} θέλει να συνδεθεί με το ρόστερ σου",
           "Ο/Η {player} ζήτησε να συνδέσει τον λογαριασμό του με παίκτη του ρόστερ σου."),
    "lt": ("{player} nori susieti su jūsų sudėtimi",
           "{player} paprašė susieti savo paskyrą su žaidėju iš jūsų sudėties."),
    "ar": ("يريد {player} الارتباط بقائمتك",
           "طلب {player} ربط حسابه بلاعب في قائمتك."),
    "he": ("{player} מבקש להתחבר לסגל שלך",
           "{player} ביקש לקשר את החשבון שלו לשחקן בסגל שלך."),
    "hi": ("{player} आपकी रोस्टर से जुड़ना चाहता है",
           "{player} ने अपने खाते को आपकी रोस्टर के किसी खिलाड़ी से जोड़ने का अनुरोध किया है।"),
    "ka": ("{player}-ს სურს დაკავშირება თქვენს შემადგენლობასთან",
           "{player}-მა მოითხოვა თავისი ანგარიშის დაკავშირება თქვენი შემადგენლობის მოთამაშესთან."),
    "ja": ("{player} さんがロスター連携を希望しています",
           "{player} さんが自分のアカウントをあなたのロスターの選手と連携させたいと申請しました。"),
    "ko": ("{player}님이 로스터 연결을 요청했습니다",
           "{player}님이 자신의 계정을 로스터의 선수와 연결하기를 요청했습니다."),
    "zh": ("{player} 想关联到你的球员名单",
           "{player} 申请将其账号关联到你名单中的一名球员。"),
    "tl": ("Gustong mag-link ni {player} sa roster mo",
           "Humiling si {player} na i-link ang kanyang account sa isang manlalaro sa roster mo."),
}


EVENTS["player_link_approved"] = {
    "en": ("You're linked to {team}",
           "Your account is now linked to your player profile on {team}."),
    "es": ("Ya estás vinculado a {team}",
           "Tu cuenta ya está vinculada a tu perfil de jugador en {team}."),
    "fr": ("Vous êtes lié à {team}",
           "Votre compte est désormais lié à votre profil de joueur dans {team}."),
    "pt": ("Está associado a {team}",
           "A sua conta está agora associada ao seu perfil de jogador em {team}."),
    "it": ("Sei collegato a {team}",
           "Il tuo account è ora collegato al tuo profilo giocatore in {team}."),
    "de": ("Du bist mit {team} verknüpft",
           "Dein Konto ist jetzt mit deinem Spielerprofil bei {team} verknüpft."),
    "nl": ("Je bent gekoppeld aan {team}",
           "Je account is nu gekoppeld aan je spelersprofiel bij {team}."),
    "sv": ("Du är kopplad till {team}",
           "Ditt konto är nu kopplat till din spelarprofil i {team}."),
    "pl": ("Jesteś połączony z {team}",
           "Twoje konto jest teraz połączone z Twoim profilem zawodnika w {team}."),
    "ru": ("Вы привязаны к {team}",
           "Ваша учётная запись привязана к вашему профилю игрока в {team}."),
    "uk": ("Вас прив'язано до {team}",
           "Ваш обліковий запис прив'язано до вашого профілю гравця в {team}."),
    "sr": ("Повезани сте са {team}",
           "Ваш налог је сада повезан са вашим играчким профилом у тиму {team}."),
    "hr": ("Povezani ste s {team}",
           "Vaš račun sada je povezan s vašim igračkim profilom u timu {team}."),
    "tr": ("{team} ile bağlantılısınız",
           "Hesabınız artık {team} takımındaki oyuncu profilinizle bağlantılı."),
    "ro": ("Ești conectat la {team}",
           "Contul tău este acum conectat la profilul tău de jucător din {team}."),
    "el": ("Συνδέθηκες με την {team}",
           "Ο λογαριασμός σου συνδέθηκε με το προφίλ παίκτη σου στην {team}."),
    "lt": ("Esate susietas su {team}",
           "Jūsų paskyra dabar susieta su jūsų žaidėjo profiliu komandoje {team}."),
    "ar": ("تم ربطك بـ {team}",
           "أصبح حسابك مرتبطًا الآن بملفك كلاعب في {team}."),
    "he": ("אתה מקושר ל־{team}",
           "החשבון שלך מקושר כעת לפרופיל השחקן שלך ב־{team}."),
    "hi": ("आप {team} से जुड़ गए हैं",
           "आपका खाता अब {team} में आपके खिलाड़ी प्रोफ़ाइल से जुड़ गया है।"),
    "ka": ("თქვენ დაკავშირებული ხართ {team}-თან",
           "თქვენი ანგარიში ახლა დაკავშირებულია თქვენს მოთამაშის პროფილთან გუნდში {team}."),
    "ja": ("{team} と連携しました",
           "あなたのアカウントが {team} の選手プロフィールと連携されました。"),
    "ko": ("{team}에 연결되었습니다",
           "계정이 {team}의 선수 프로필과 연결되었습니다."),
    "zh": ("你已关联到 {team}",
           "你的账号已关联到你在 {team} 的球员档案。"),
    "tl": ("Naka-link ka na sa {team}",
           "Naka-link na ang account mo sa iyong player profile sa {team}."),
}


EVENTS["report_shared"] = {
    "en": ("{sender} shared a report with you",
           "{sender} shared a {report} with you on BloomPrint."),
    "es": ("{sender} ha compartido un informe contigo",
           "{sender} ha compartido un {report} contigo en BloomPrint."),
    "fr": ("{sender} a partagé un rapport avec vous",
           "{sender} a partagé un {report} avec vous sur BloomPrint."),
    "pt": ("{sender} partilhou um relatório consigo",
           "{sender} partilhou um {report} consigo no BloomPrint."),
    "it": ("{sender} ha condiviso un report con te",
           "{sender} ha condiviso un {report} con te su BloomPrint."),
    "de": ("{sender} hat einen Bericht mit dir geteilt",
           "{sender} hat einen {report} auf BloomPrint mit dir geteilt."),
    "nl": ("{sender} heeft een rapport met je gedeeld",
           "{sender} heeft een {report} met je gedeeld op BloomPrint."),
    "sv": ("{sender} delade en rapport med dig",
           "{sender} delade en {report} med dig på BloomPrint."),
    "pl": ("{sender} udostępnił Ci raport",
           "{sender} udostępnił Ci {report} w BloomPrint."),
    "ru": ("{sender} поделился с вами отчётом",
           "{sender} поделился с вами материалом «{report}» в BloomPrint."),
    "uk": ("{sender} поділився з вами звітом",
           "{sender} поділився з вами матеріалом «{report}» у BloomPrint."),
    "sr": ("{sender} је поделио извештај са вама",
           "{sender} је поделио {report} са вама на BloomPrint-у."),
    "hr": ("{sender} je podijelio izvještaj s vama",
           "{sender} je podijelio {report} s vama na BloomPrintu."),
    "tr": ("{sender} sizinle bir rapor paylaştı",
           "{sender} BloomPrint'te sizinle bir {report} paylaştı."),
    "ro": ("{sender} a partajat un raport cu tine",
           "{sender} a partajat un {report} cu tine pe BloomPrint."),
    "el": ("Ο/Η {sender} μοιράστηκε μια αναφορά μαζί σου",
           "Ο/Η {sender} μοιράστηκε ένα {report} μαζί σου στο BloomPrint."),
    "lt": ("{sender} pasidalijo su jumis ataskaita",
           "{sender} pasidalijo su jumis {report} BloomPrint sistemoje."),
    "ar": ("شارك {sender} تقريرًا معك",
           "شارك {sender} معك {report} على BloomPrint."),
    "he": ("{sender} שיתף איתך דוח",
           "{sender} שיתף איתך {report} ב־BloomPrint."),
    "hi": ("{sender} ने आपके साथ एक रिपोर्ट साझा की",
           "{sender} ने BloomPrint पर आपके साथ एक {report} साझा की है।"),
    "ka": ("{sender}-მა გაგიზიარათ ანგარიში",
           "{sender}-მა გაგიზიარათ {report} BloomPrint-ზე."),
    "ja": ("{sender} さんがレポートを共有しました",
           "{sender} さんが BloomPrint で {report} をあなたと共有しました。"),
    "ko": ("{sender}님이 리포트를 공유했습니다",
           "{sender}님이 BloomPrint에서 {report}을(를) 공유했습니다."),
    "zh": ("{sender} 与你分享了一份报告",
           "{sender} 在 BloomPrint 上与你分享了一份{report}。"),
    "tl": ("Nagbahagi si {sender} ng report sa iyo",
           "Nagbahagi si {sender} ng {report} sa iyo sa BloomPrint."),
}


EVENTS["report_request"] = {
    "en": ("{sender} requested a report",
           "{sender} asked you for a {report}."),
    "es": ("{sender} ha solicitado un informe",
           "{sender} te ha pedido un {report}."),
    "fr": ("{sender} a demandé un rapport",
           "{sender} vous a demandé un {report}."),
    "pt": ("{sender} solicitou um relatório",
           "{sender} pediu-lhe um {report}."),
    "it": ("{sender} ha richiesto un report",
           "{sender} ti ha chiesto un {report}."),
    "de": ("{sender} hat einen Bericht angefragt",
           "{sender} hat dich um einen {report} gebeten."),
    "nl": ("{sender} heeft een rapport aangevraagd",
           "{sender} heeft je om een {report} gevraagd."),
    "sv": ("{sender} har begärt en rapport",
           "{sender} har bett dig om en {report}."),
    "pl": ("{sender} poprosił o raport",
           "{sender} poprosił Cię o {report}."),
    "ru": ("{sender} запросил отчёт",
           "{sender} попросил у вас материал «{report}»."),
    "uk": ("{sender} запитав звіт",
           "{sender} попросив у вас матеріал «{report}»."),
    "sr": ("{sender} је затражио извештај",
           "{sender} је од вас затражио {report}."),
    "hr": ("{sender} je zatražio izvještaj",
           "{sender} je od vas zatražio {report}."),
    "tr": ("{sender} bir rapor istedi",
           "{sender} sizden bir {report} istedi."),
    "ro": ("{sender} a cerut un raport",
           "{sender} ți-a cerut un {report}."),
    "el": ("Ο/Η {sender} ζήτησε μια αναφορά",
           "Ο/Η {sender} σου ζήτησε ένα {report}."),
    "lt": ("{sender} paprašė ataskaitos",
           "{sender} paprašė jūsų {report}."),
    "ar": ("طلب {sender} تقريرًا",
           "طلب منك {sender} {report}."),
    "he": ("{sender} ביקש דוח",
           "{sender} ביקש ממך {report}."),
    "hi": ("{sender} ने एक रिपोर्ट माँगी",
           "{sender} ने आपसे एक {report} माँगी है।"),
    "ka": ("{sender}-მა მოითხოვა ანგარიში",
           "{sender}-მა მოგთხოვათ {report}."),
    "ja": ("{sender} さんがレポートを依頼しました",
           "{sender} さんがあなたに {report} を依頼しました。"),
    "ko": ("{sender}님이 리포트를 요청했습니다",
           "{sender}님이 {report}을(를) 요청했습니다."),
    "zh": ("{sender} 请求一份报告",
           "{sender} 向你请求一份{report}。"),
    "tl": ("Humiling si {sender} ng report",
           "Humiling sa iyo si {sender} ng {report}."),
}


EVENTS["report_declined"] = {
    "en": ("{sender} declined your report request",
           "{sender} declined your request for a {report}."),
    "es": ("{sender} ha rechazado tu solicitud de informe",
           "{sender} ha rechazado tu solicitud de un {report}."),
    "fr": ("{sender} a refusé votre demande de rapport",
           "{sender} a refusé votre demande de {report}."),
    "pt": ("{sender} recusou o seu pedido de relatório",
           "{sender} recusou o seu pedido de um {report}."),
    "it": ("{sender} ha rifiutato la tua richiesta",
           "{sender} ha rifiutato la tua richiesta di un {report}."),
    "de": ("{sender} hat deine Anfrage abgelehnt",
           "{sender} hat deine Anfrage für einen {report} abgelehnt."),
    "nl": ("{sender} heeft je aanvraag afgewezen",
           "{sender} heeft je aanvraag voor een {report} afgewezen."),
    "sv": ("{sender} avböjde din begäran",
           "{sender} avböjde din begäran om en {report}."),
    "pl": ("{sender} odrzucił Twoją prośbę",
           "{sender} odrzucił Twoją prośbę o {report}."),
    "ru": ("{sender} отклонил ваш запрос",
           "{sender} отклонил ваш запрос на материал «{report}»."),
    "uk": ("{sender} відхилив ваш запит",
           "{sender} відхилив ваш запит на матеріал «{report}»."),
    "sr": ("{sender} је одбио ваш захтев",
           "{sender} је одбио ваш захтев за {report}."),
    "hr": ("{sender} je odbio vaš zahtjev",
           "{sender} je odbio vaš zahtjev za {report}."),
    "tr": ("{sender} isteğinizi reddetti",
           "{sender} {report} isteğinizi reddetti."),
    "ro": ("{sender} ți-a respins cererea",
           "{sender} ți-a respins cererea pentru un {report}."),
    "el": ("Ο/Η {sender} απέρριψε το αίτημά σου",
           "Ο/Η {sender} απέρριψε το αίτημά σου για ένα {report}."),
    "lt": ("{sender} atmetė jūsų prašymą",
           "{sender} atmetė jūsų prašymą dėl {report}."),
    "ar": ("رفض {sender} طلبك",
           "رفض {sender} طلبك للحصول على {report}."),
    "he": ("{sender} דחה את בקשתך",
           "{sender} דחה את בקשתך ל{report}."),
    "hi": ("{sender} ने आपका अनुरोध अस्वीकार किया",
           "{sender} ने {report} के लिए आपका अनुरोध अस्वीकार कर दिया।"),
    "ka": ("{sender}-მა უარყო თქვენი მოთხოვნა",
           "{sender}-მა უარყო თქვენი მოთხოვნა {report}-ზე."),
    "ja": ("{sender} さんが依頼を辞退しました",
           "{sender} さんが {report} の依頼を辞退しました。"),
    "ko": ("{sender}님이 요청을 거절했습니다",
           "{sender}님이 {report} 요청을 거절했습니다."),
    "zh": ("{sender} 拒绝了你的请求",
           "{sender} 拒绝了你索取{report}的请求。"),
    "tl": ("Tinanggihan ni {sender} ang hiling mo",
           "Tinanggihan ni {sender} ang hiling mo para sa {report}."),
}


EVENTS["training_assigned"] = {
    "en": ("New training program: {title}",
           "{coach} assigned you a training program: {title}."),
    "es": ("Nuevo programa de entrenamiento: {title}",
           "{coach} te ha asignado un programa de entrenamiento: {title}."),
    "fr": ("Nouveau programme d'entraînement : {title}",
           "{coach} vous a attribué un programme d'entraînement : {title}."),
    "pt": ("Novo programa de treino: {title}",
           "{coach} atribuiu-lhe um programa de treino: {title}."),
    "it": ("Nuovo programma di allenamento: {title}",
           "{coach} ti ha assegnato un programma di allenamento: {title}."),
    "de": ("Neues Trainingsprogramm: {title}",
           "{coach} hat dir ein Trainingsprogramm zugewiesen: {title}."),
    "nl": ("Nieuw trainingsprogramma: {title}",
           "{coach} heeft je een trainingsprogramma toegewezen: {title}."),
    "sv": ("Nytt träningsprogram: {title}",
           "{coach} har tilldelat dig ett träningsprogram: {title}."),
    "pl": ("Nowy program treningowy: {title}",
           "{coach} przypisał Ci program treningowy: {title}."),
    "ru": ("Новая тренировочная программа: {title}",
           "{coach} назначил вам тренировочную программу: {title}."),
    "uk": ("Нова тренувальна програма: {title}",
           "{coach} призначив вам тренувальну програму: {title}."),
    "sr": ("Нови програм тренинга: {title}",
           "{coach} вам је доделио програм тренинга: {title}."),
    "hr": ("Novi program treninga: {title}",
           "{coach} vam je dodijelio program treninga: {title}."),
    "tr": ("Yeni antrenman programı: {title}",
           "{coach} size bir antrenman programı atadı: {title}."),
    "ro": ("Program nou de antrenament: {title}",
           "{coach} ți-a atribuit un program de antrenament: {title}."),
    "el": ("Νέο πρόγραμμα προπόνησης: {title}",
           "Ο/Η {coach} σου ανέθεσε ένα πρόγραμμα προπόνησης: {title}."),
    "lt": ("Nauja treniruočių programa: {title}",
           "{coach} priskyrė jums treniruočių programą: {title}."),
    "ar": ("برنامج تدريبي جديد: {title}",
           "أسند إليك {coach} برنامجًا تدريبيًا: {title}."),
    "he": ("תוכנית אימון חדשה: {title}",
           "{coach} הקצה לך תוכנית אימון: {title}."),
    "hi": ("नया प्रशिक्षण कार्यक्रम: {title}",
           "{coach} ने आपको एक प्रशिक्षण कार्यक्रम सौंपा है: {title}।"),
    "ka": ("ახალი სავარჯიშო პროგრამა: {title}",
           "{coach}-მა მოგანიჭათ სავარჯიშო პროგრამა: {title}."),
    "ja": ("新しいトレーニングプログラム: {title}",
           "{coach} さんがトレーニングプログラムを割り当てました: {title}。"),
    "ko": ("새 훈련 프로그램: {title}",
           "{coach}님이 훈련 프로그램을 배정했습니다: {title}."),
    "zh": ("新的训练计划：{title}",
           "{coach} 为你分配了一份训练计划：{title}。"),
    "tl": ("Bagong training program: {title}",
           "Binigyan ka ni {coach} ng training program: {title}."),
}


EVENTS["signup_coach"] = {
    "en": ("Welcome to BloomPrint",
           "BloomPrint writes player evaluations, scouting reports, game reports and training programs from your roster and the games you track.\n\nWhere to start.\n\n1. Fill in **System & Philosophy** on your profile. Describe your system and what you value in a player. The AI applies it to every report and every training program it writes, so the more you put in, the more closely the writing is framed around your system and how a player fits your team.\n\n2. Create a team and add your **roster**. Type players in one at a time, or upload any file and let the AI read it.\n\n3. Open a **player** and run an evaluation. The AI grades them against the six pillars, offense, defense, physical, intangibles, advanced and strategic fit, and gives you the reasoning behind every grade.\n\n4. Build a packet in **Team Eval/Packet**. Pull in film, the stats from a game you tracked and your scouting notes on the opponent, and the AI writes one report across all of it. Pick more than one report type and it combines them into a single document.\n\n**Ask BloomPrint** reads your own data to answer questions, and it assists you with the work:\n\n- Who are my top-graded players right now?\n- Which opponents did we struggle with?\n- Scout our next opponent\n- Build a coaching report for my team\n- How do I import a roster?"),
    "es": ('Bienvenido a BloomPrint',
           'BloomPrint escribe evaluaciones de jugadores, informes de ojeo, informes de partido y programas de entrenamiento a partir de tu plantilla y de los partidos que registras.\n\nPor dónde empezar.\n\n1. Completa **Sistema y Filosofía** en tu perfil. Describe tu sistema y lo que valoras en un jugador. La IA lo aplica a cada informe y a cada programa de entrenamiento que escribe, así que cuanto más pongas, más se ajustará el texto a tu sistema y a cómo encaja un jugador en tu equipo.\n\n2. Crea un equipo y añade tu **plantilla**. Escribe los jugadores uno a uno o sube cualquier archivo y deja que la IA lo lea.\n\n3. Abre un **jugador** y haz una evaluación. La IA lo califica en los seis pilares: ataque, defensa, físico, intangibles, avanzado y encaje estratégico, y te da el razonamiento de cada nota.\n\n4. Crea un dossier en **Team Eval/Packet**. Añade vídeo, las estadísticas de un partido que hayas registrado y tus notas de ojeo sobre el rival, y la IA escribe un único informe con todo ello. Elige más de un tipo de informe y los combina en un solo documento.\n\n**Ask BloomPrint** lee tus propios datos para responder preguntas y te ayuda con el trabajo:\n\n- ¿Quiénes son mis jugadores mejor calificados ahora mismo?\n- ¿Con qué rivales nos costó más?\n- Analiza a nuestro próximo rival\n- Crea un informe de entrenador para mi equipo\n- ¿Cómo importo una plantilla?'),
    "fr": ('Bienvenue sur BloomPrint',
           "BloomPrint rédige des évaluations de joueurs, des rapports de détection, des rapports de match et des programmes d'entraînement à partir de votre effectif et des matchs que vous suivez.\n\nPar où commencer.\n\n1. Remplissez **Système et Philosophie** dans votre profil. Décrivez votre système et ce que vous recherchez chez un joueur. L'IA l'applique à chaque rapport et à chaque programme qu'elle rédige, donc plus vous en mettez, plus le texte épouse votre système et la façon dont un joueur s'y intègre.\n\n2. Créez une équipe et ajoutez votre **effectif**. Saisissez les joueurs un par un, ou importez n'importe quel fichier et laissez l'IA le lire.\n\n3. Ouvrez un **joueur** et lancez une évaluation. L'IA le note sur les six piliers : attaque, défense, physique, intangibles, analyse avancée et adéquation stratégique, avec le raisonnement derrière chaque note.\n\n4. Créez un dossier dans **Team Eval/Packet**. Ajoutez la vidéo, les statistiques d'un match que vous avez suivi et vos notes de détection sur l'adversaire : l'IA en tire un seul rapport. Choisissez plusieurs types de rapport et elle les réunit en un document.\n\n**Ask BloomPrint** lit vos propres données pour répondre à vos questions et vous assiste dans le travail :\n\n- Quels sont mes joueurs les mieux notés en ce moment ?\n- Contre quels adversaires avons-nous eu du mal ?\n- Analyse notre prochain adversaire\n- Rédige un rapport d'entraîneur pour mon équipe\n- Comment importer un effectif ?"),
    "pt": ('Bem-vindo ao BloomPrint',
           'O BloomPrint escreve avaliações de jogadores, relatórios de observação, relatórios de jogo e programas de treino a partir do seu plantel e dos jogos que acompanha.\n\nPor onde começar.\n\n1. Preencha **Sistema e Filosofia** no seu perfil. Descreva o seu sistema e o que valoriza num jogador. A IA aplica isso a cada relatório e a cada programa de treino que escreve, por isso quanto mais puser, mais o texto se molda ao seu sistema e ao encaixe do jogador na equipa.\n\n2. Crie uma equipa e adicione o seu **plantel**. Escreva os jogadores um a um ou carregue qualquer ficheiro e deixe a IA lê-lo.\n\n3. Abra um **jogador** e faça uma avaliação. A IA classifica-o nos seis pilares: ataque, defesa, físico, intangíveis, análise avançada e encaixe estratégico, com o raciocínio por trás de cada nota.\n\n4. Construa um dossiê em **Team Eval/Packet**. Junte vídeo, as estatísticas de um jogo que acompanhou e as suas notas de observação sobre o adversário, e a IA escreve um único relatório com tudo. Escolha mais do que um tipo de relatório e ela combina-os num só documento.\n\n**Ask BloomPrint** lê os seus próprios dados para responder a perguntas e ajuda-o no trabalho:\n\n- Quais são os meus jogadores com melhor nota neste momento?\n- Com que adversários tivemos mais dificuldade?\n- Observa o nosso próximo adversário\n- Cria um relatório de treinador para a minha equipa\n- Como importo um plantel?'),
    "it": ('Benvenuto su BloomPrint',
           "BloomPrint scrive valutazioni dei giocatori, report di scouting, report partita e programmi di allenamento partendo dal tuo roster e dalle partite che segui.\n\nDa dove iniziare.\n\n1. Compila **Sistema e Filosofia** nel tuo profilo. Descrivi il tuo sistema e cosa cerchi in un giocatore. L'IA lo applica a ogni report e a ogni programma che scrive, quindi più ci metti, più il testo si modella sul tuo sistema e su come un giocatore si inserisce nella squadra.\n\n2. Crea una squadra e aggiungi il tuo **roster**. Inserisci i giocatori uno alla volta oppure carica un file qualsiasi e lascia che l'IA lo legga.\n\n3. Apri un **giocatore** e avvia una valutazione. L'IA lo valuta sui sei pilastri: attacco, difesa, fisico, intangibili, analisi avanzata e adattamento strategico, con il ragionamento dietro ogni voto.\n\n4. Costruisci un dossier in **Team Eval/Packet**. Aggiungi il video, le statistiche di una partita che hai seguito e i tuoi appunti di scouting sull'avversario: l'IA scrive un unico report su tutto. Scegli più tipi di report e li unisce in un solo documento.\n\n**Ask BloomPrint** legge i tuoi dati per rispondere alle domande e ti assiste nel lavoro:\n\n- Chi sono i miei giocatori con la valutazione più alta adesso?\n- Con quali avversari abbiamo faticato?\n- Studia il nostro prossimo avversario\n- Crea un report per la mia squadra\n- Come importo un roster?"),
    "de": ('Willkommen bei BloomPrint',
           'BloomPrint schreibt Spielerbewertungen, Scouting-Berichte, Spielberichte und Trainingsprogramme aus deinem Kader und den Spielen, die du erfasst.\n\nWo du anfängst.\n\n1. Fülle **System & Philosophie** in deinem Profil aus. Beschreibe dein System und worauf du bei einem Spieler achtest. Die KI wendet das auf jeden Bericht und jedes Trainingsprogramm an, das sie schreibt: je mehr du hinterlegst, desto stärker richtet sich der Text nach deinem System und danach, wie ein Spieler ins Team passt.\n\n2. Lege ein Team an und füge deinen **Kader** hinzu. Trage die Spieler einzeln ein oder lade eine beliebige Datei hoch und lass die KI sie lesen.\n\n3. Öffne einen **Spieler** und erstelle eine Bewertung. Die KI benotet ihn in den sechs Säulen: Offensive, Defensive, Physis, Intangibles, Advanced und strategische Passung, samt Begründung für jede Note.\n\n4. Baue ein Paket in **Team Eval/Packet**. Bring Filmmaterial, die Statistik eines erfassten Spiels und deine Scouting-Notizen zum Gegner zusammen, und die KI schreibt daraus einen Bericht. Wähl mehrere Berichtsarten, und sie fasst sie zu einem Dokument zusammen.\n\n**Ask BloomPrint** liest deine eigenen Daten, beantwortet Fragen und hilft dir bei der Arbeit:\n\n- Wer sind gerade meine bestbewerteten Spieler?\n- Gegen welche Gegner hatten wir Probleme?\n- Scoute unseren nächsten Gegner\n- Erstelle einen Trainerbericht für mein Team\n- Wie importiere ich einen Kader?'),
    "nl": ('Welkom bij BloomPrint',
           "BloomPrint schrijft spelersevaluaties, scoutingrapporten, wedstrijdrapporten en trainingsprogramma's op basis van je selectie en de wedstrijden die je bijhoudt.\n\nWaar te beginnen.\n\n1. Vul **Systeem & Filosofie** in op je profiel. Beschrijf je systeem en waar je op let bij een speler. De AI past dat toe op elk rapport en elk trainingsprogramma dat ze schrijft, dus hoe meer je invult, hoe dichter de tekst bij jouw systeem blijft en bij hoe een speler in je ploeg past.\n\n2. Maak een team aan en voeg je **selectie** toe. Typ spelers één voor één in, of upload een willekeurig bestand en laat de AI het lezen.\n\n3. Open een **speler** en maak een evaluatie. De AI beoordeelt hem op de zes pijlers: aanval, verdediging, fysiek, intangibles, advanced en strategische fit, met de redenering achter elk cijfer.\n\n4. Bouw een pakket in **Team Eval/Packet**. Voeg beelden toe, de statistieken van een wedstrijd die je hebt bijgehouden en je scoutingnotities over de tegenstander: de AI schrijft er één rapport uit. Kies meerdere rapporttypes en ze voegt ze samen tot één document.\n\n**Ask BloomPrint** leest je eigen gegevens om vragen te beantwoorden en helpt je met het werk:\n\n- Wie zijn nu mijn hoogst beoordeelde spelers?\n- Tegen welke tegenstanders hadden we het moeilijk?\n- Scout onze volgende tegenstander\n- Maak een coachrapport voor mijn team\n- Hoe importeer ik een selectie?"),
    "sv": ('Välkommen till BloomPrint',
           'BloomPrint skriver spelarutvärderingar, scoutingrapporter, matchrapporter och träningsprogram utifrån din trupp och de matcher du följer.\n\nVar du börjar.\n\n1. Fyll i **System och filosofi** i din profil. Beskriv ditt system och vad du värderar hos en spelare. AI:n tillämpar det på varje rapport och varje träningsprogram den skriver, så ju mer du lägger in, desto närmare följer texten ditt system och hur en spelare passar i laget.\n\n2. Skapa ett lag och lägg till din **trupp**. Skriv in spelarna en och en, eller ladda upp vilken fil som helst och låt AI:n läsa den.\n\n3. Öppna en **spelare** och gör en utvärdering. AI:n betygsätter hen i de sex pelarna: offensiv, försvar, fysik, intangibles, advanced och strategisk passform, med resonemanget bakom varje betyg.\n\n4. Bygg ett paket i **Team Eval/Packet**. Ta in film, statistiken från en match du följt och dina scoutinganteckningar om motståndaren, så skriver AI:n en samlad rapport. Välj flera rapporttyper så slår den ihop dem till ett dokument.\n\n**Ask BloomPrint** läser dina egna data för att svara på frågor och hjälper dig med arbetet:\n\n- Vilka är mina högst betygsatta spelare just nu?\n- Vilka motståndare hade vi svårt mot?\n- Scouta vår nästa motståndare\n- Skriv en tränarrapport för mitt lag\n- Hur importerar jag en trupp?'),
    "pl": ('Witamy w BloomPrint',
           'BloomPrint pisze oceny zawodników, raporty skautingowe, raporty meczowe i programy treningowe na podstawie Twojego składu i meczów, które rejestrujesz.\n\nOd czego zacząć.\n\n1. Uzupełnij **System i filozofię** w swoim profilu. Opisz swój system i to, czego szukasz u zawodnika. AI stosuje to w każdym raporcie i każdym programie treningowym, więc im więcej wpiszesz, tym bliżej tekst trzyma się Twojego systemu i tego, jak zawodnik pasuje do zespołu.\n\n2. Utwórz zespół i dodaj **skład**. Wpisz zawodników pojedynczo albo wgraj dowolny plik i pozwól AI go odczytać.\n\n3. Otwórz **zawodnika** i wykonaj ocenę. AI ocenia go w sześciu filarach: atak, obrona, fizyczność, cechy niemierzalne, analiza zaawansowana i dopasowanie strategiczne, wraz z uzasadnieniem każdej oceny.\n\n4. Zbuduj pakiet w **Team Eval/Packet**. Dodaj wideo, statystyki zarejestrowanego meczu i swoje notatki skautingowe o rywalu, a AI napisze z tego jeden raport. Wybierz więcej niż jeden typ raportu, a połączy je w jeden dokument.\n\n**Ask BloomPrint** czyta Twoje dane, odpowiada na pytania i pomaga w pracy:\n\n- Którzy zawodnicy mają teraz najwyższe oceny?\n- Z którymi rywalami mieliśmy problemy?\n- Przeskautuj naszego następnego rywala\n- Napisz raport trenerski dla mojego zespołu\n- Jak zaimportować skład?'),
    "ru": ('Добро пожаловать в BloomPrint',
           'BloomPrint пишет оценки игроков, скаутинг-отчёты, отчёты о матчах и тренировочные программы на основе вашего состава и матчей, которые вы фиксируете.\n\nС чего начать.\n\n1. Заполните **Систему и философию** в профиле. Опишите, во что вы играете и что цените в игроке. ИИ применяет это к каждому отчёту и каждой тренировочной программе, поэтому чем больше вы укажете, тем ближе текст будет к вашей системе и к тому, как игрок в неё вписывается.\n\n2. Создайте команду и добавьте **состав**. Введите игроков по одному или загрузите любой файл и позвольте ИИ прочитать его.\n\n3. Откройте **игрока** и сделайте оценку. ИИ оценивает его по шести опорам: нападение, защита, физика, неизмеримое, продвинутая аналитика и стратегическое соответствие, с обоснованием каждой оценки.\n\n4. Соберите пакет в **Team Eval/Packet**. Добавьте видео, статистику зафиксированного матча и свои скаутинг-заметки о сопернике, и ИИ напишет по всему этому один отчёт. Выберите несколько типов отчёта, и он объединит их в один документ.\n\n**Ask BloomPrint** читает ваши данные, отвечает на вопросы и помогает в работе:\n\n- Кто сейчас мои игроки с лучшими оценками?\n- С какими соперниками нам было тяжело?\n- Разбери нашего следующего соперника\n- Составь тренерский отчёт для команды\n- Как импортировать состав?'),
    "uk": ('Ласкаво просимо до BloomPrint',
           "BloomPrint пише оцінки гравців, скаутингові звіти, звіти про матчі та тренувальні програми на основі вашого складу і матчів, які ви фіксуєте.\n\nЗ чого почати.\n\n1. Заповніть **Систему і філософію** у профілі. Опишіть, у що ви граєте і що цінуєте в гравцеві. ШІ застосовує це до кожного звіту й кожної тренувальної програми, тож що більше ви вкажете, то ближчим буде текст до вашої системи і до того, як гравець у неї вписується.\n\n2. Створіть команду та додайте **склад**. Введіть гравців по одному або завантажте будь-який файл і дайте ШІ його прочитати.\n\n3. Відкрийте **гравця** і зробіть оцінку. ШІ оцінює його за шістьма опорами: напад, захист, фізика, невимірне, поглиблена аналітика та стратегічна відповідність, з обґрунтуванням кожної оцінки.\n\n4. Зберіть пакет у **Team Eval/Packet**. Додайте відео, статистику зафіксованого матчу та свої скаутингові нотатки про суперника, і ШІ напише з усього цього один звіт. Виберіть кілька типів звіту, і він об'єднає їх в один документ.\n\n**Ask BloomPrint** читає ваші дані, відповідає на запитання і допомагає в роботі:\n\n- Хто зараз мої найкраще оцінені гравці?\n- З якими суперниками нам було важко?\n- Розбери нашого наступного суперника\n- Склади тренерський звіт для команди\n- Як імпортувати склад?"),
    "sr": ('Добро дошли у BloomPrint',
           'BloomPrint пише оцене играча, скаут извештаје, извештаје о утакмицама и тренажне програме на основу вашег састава и утакмица које пратите.\n\nОдакле почети.\n\n1. Попуните **Систем и филозофију** у профилу. Опишите шта играте и шта цените код играча. ВИ то примењује на сваки извештај и сваки тренажни програм, па што више унесете, то ће текст бити ближи вашем систему и томе како се играч у њега уклапа.\n\n2. Направите тим и додајте **састав**. Унесите играче једног по једног или отпремите било који фајл и пустите ВИ да га прочита.\n\n3. Отворите **играча** и урадите оцену. ВИ га оцењује по шест стубова: напад, одбрана, физика, немерљиво, напредна анализа и стратешка уклопивост, уз образложење сваке оцене.\n\n4. Направите пакет у **Team Eval/Packet**. Додајте снимак, статистику утакмице коју сте пратили и своје скаут белешке о противнику, и ВИ ће написати један извештај о свему томе. Изаберите више типова извештаја и спојиће их у један документ.\n\n**Ask BloomPrint** чита ваше податке, одговара на питања и помаже вам у раду:\n\n- Ко су сада моји најбоље оцењени играчи?\n- Са којим противницима смо се мучили?\n- Проучи нашег следећег противника\n- Направи тренерски извештај за мој тим\n- Како да увезем састав?'),
    "hr": ('Dobrodošli u BloomPrint',
           'BloomPrint piše ocjene igrača, skautske izvještaje, izvještaje o utakmicama i programe treninga na temelju vašeg sastava i utakmica koje pratite.\n\nOdakle početi.\n\n1. Ispunite **Sustav i filozofiju** u profilu. Opišite što igrate i što cijenite kod igrača. UI to primjenjuje na svaki izvještaj i svaki program treninga, pa što više unesete, to će tekst biti bliži vašem sustavu i tome kako se igrač u njega uklapa.\n\n2. Napravite momčad i dodajte **sastav**. Unesite igrače jednog po jednog ili prenesite bilo koju datoteku i pustite UI da je pročita.\n\n3. Otvorite **igrača** i napravite ocjenu. UI ga ocjenjuje po šest stupova: napad, obrana, fizika, nemjerljivo, napredna analiza i strateška uklopivost, uz obrazloženje svake ocjene.\n\n4. Složite paket u **Team Eval/Packet**. Dodajte snimku, statistiku utakmice koju ste pratili i svoje skautske bilješke o protivniku, i UI će o svemu tome napisati jedan izvještaj. Odaberite više vrsta izvještaja i spojit će ih u jedan dokument.\n\n**Ask BloomPrint** čita vaše podatke, odgovara na pitanja i pomaže vam u radu:\n\n- Tko su sada moji najbolje ocijenjeni igrači?\n- S kojim smo se protivnicima mučili?\n- Prouči našeg sljedećeg protivnika\n- Napravi trenerski izvještaj za moju momčad\n- Kako uvesti sastav?'),
    "tr": ("BloomPrint'e hoş geldiniz",
           'BloomPrint, kadronuzdan ve takip ettiğiniz maçlardan oyuncu değerlendirmeleri, gözlem raporları, maç raporları ve antrenman programları yazar.\n\nNereden başlamalı.\n\n1. Profilinizde **Sistem ve Felsefe** bölümünü doldurun. Ne oynattığınızı ve bir oyuncuda neye değer verdiğinizi anlatın. Yapay zekâ bunu yazdığı her rapora ve her antrenman programına uygular; ne kadar çok yazarsanız metin sisteminize ve oyuncunun takıma uyumuna o kadar yaklaşır.\n\n2. Bir takım oluşturun ve **kadronuzu** ekleyin. Oyuncuları tek tek yazın ya da herhangi bir dosya yükleyip yapay zekânın okumasına bırakın.\n\n3. Bir **oyuncu** açıp değerlendirme yapın. Yapay zekâ onu altı sütunda notlandırır: hücum, savunma, fizik, ölçülemeyenler, ileri analiz ve stratejik uyum; her notun gerekçesiyle birlikte.\n\n4. **Team Eval/Packet** içinde bir paket oluşturun. Görüntüyü, takip ettiğiniz bir maçın istatistiklerini ve rakip hakkındaki gözlem notlarınızı bir araya getirin; yapay zekâ hepsinden tek bir rapor yazar. Birden fazla rapor türü seçerseniz onları tek belgede birleştirir.\n\n**Ask BloomPrint** kendi verilerinizi okuyup soruları yanıtlar ve işte size yardım eder:\n\n- Şu anda en yüksek notlu oyuncularım kimler?\n- Hangi rakiplere karşı zorlandık?\n- Bir sonraki rakibimizi incele\n- Takımım için bir teknik rapor hazırla\n- Kadroyu nasıl içe aktarırım?'),
    "ro": ('Bine ai venit pe BloomPrint',
           'BloomPrint scrie evaluări de jucători, rapoarte de scouting, rapoarte de meci și programe de antrenament pornind de la lotul tău și de la meciurile pe care le înregistrezi.\n\nDe unde începi.\n\n1. Completează **Sistem și Filozofie** în profil. Descrie ce joci și ce cauți la un jucător. IA aplică asta fiecărui raport și fiecărui program de antrenament pe care îl scrie, așa că cu cât pui mai mult, cu atât textul urmează mai îndeaproape sistemul tău și felul în care un jucător se potrivește echipei.\n\n2. Creează o echipă și adaugă-ți **lotul**. Scrie jucătorii unul câte unul sau încarcă orice fișier și lasă IA să îl citească.\n\n3. Deschide un **jucător** și fă o evaluare. IA îl notează pe cei șase piloni: atac, apărare, fizic, intangibile, analiză avansată și potrivire strategică, cu raționamentul din spatele fiecărei note.\n\n4. Construiește un pachet în **Team Eval/Packet**. Adaugă filmări, statisticile unui meci pe care l-ai urmărit și notele tale de scouting despre adversar, iar IA scrie un singur raport din tot. Alege mai multe tipuri de raport și le combină într-un singur document.\n\n**Ask BloomPrint** îți citește propriile date, răspunde la întrebări și te ajută la treabă:\n\n- Care sunt acum jucătorii mei cu cele mai bune note?\n- Cu ce adversari ne-am chinuit?\n- Analizează următorul nostru adversar\n- Fă un raport de antrenor pentru echipa mea\n- Cum import un lot?'),
    "el": ('Καλώς ήρθες στο BloomPrint',
           'Το BloomPrint γράφει αξιολογήσεις παικτών, αναφορές σκάουτινγκ, αναφορές αγώνων και προγράμματα προπόνησης από το ρόστερ σας και από τους αγώνες που καταγράφετε.\n\nΑπό πού ξεκινάτε.\n\n1. Συμπληρώστε το **Σύστημα και Φιλοσοφία** στο προφίλ σας. Περιγράψτε τι παίζετε και τι εκτιμάτε σε έναν παίκτη. Η ΤΝ το εφαρμόζει σε κάθε αναφορά και σε κάθε πρόγραμμα προπόνησης που γράφει, οπότε όσο περισσότερα βάλετε, τόσο πιο κοντά μένει το κείμενο στο σύστημά σας και στο πώς ταιριάζει ένας παίκτης στην ομάδα.\n\n2. Δημιουργήστε ομάδα και προσθέστε το **ρόστερ** σας. Γράψτε τους παίκτες έναν έναν ή ανεβάστε οποιοδήποτε αρχείο και αφήστε την ΤΝ να το διαβάσει.\n\n3. Ανοίξτε έναν **παίκτη** και κάντε αξιολόγηση. Η ΤΝ τον βαθμολογεί στους έξι πυλώνες: επίθεση, άμυνα, φυσικά προσόντα, άυλα, προχωρημένη ανάλυση και στρατηγική εφαρμογή, με το σκεπτικό πίσω από κάθε βαθμό.\n\n4. Φτιάξτε έναν φάκελο στο **Team Eval/Packet**. Βάλτε βίντεο, τα στατιστικά ενός αγώνα που καταγράψατε και τις σημειώσεις σας για τον αντίπαλο, και η ΤΝ γράφει μία αναφορά από όλα αυτά. Επιλέξτε περισσότερους από έναν τύπους αναφοράς και τους ενώνει σε ένα έγγραφο.\n\nΤο **Ask BloomPrint** διαβάζει τα δικά σας δεδομένα, απαντά σε ερωτήσεις και σας βοηθά στη δουλειά:\n\n- Ποιοι είναι τώρα οι παίκτες μου με την καλύτερη βαθμολογία;\n- Με ποιους αντιπάλους δυσκολευτήκαμε;\n- Ανάλυσε τον επόμενο αντίπαλό μας\n- Φτιάξε μια αναφορά προπονητή για την ομάδα μου\n- Πώς εισάγω ένα ρόστερ;'),
    "lt": ('Sveiki atvykę į BloomPrint',
           'BloomPrint rašo žaidėjų vertinimus, skautavimo ataskaitas, rungtynių ataskaitas ir treniruočių programas iš jūsų sudėties ir rungtynių, kurias fiksuojate.\n\nNuo ko pradėti.\n\n1. Užpildykite **Sistemą ir filosofiją** savo profilyje. Aprašykite, ką žaidžiate ir ko ieškote žaidėjuje. DI tai pritaiko kiekvienai ataskaitai ir kiekvienai treniruočių programai, kurią rašo, tad kuo daugiau įrašysite, tuo arčiau tekstas laikysis jūsų sistemos ir to, kaip žaidėjas į ją įsilieja.\n\n2. Sukurkite komandą ir pridėkite **sudėtį**. Suveskite žaidėjus po vieną arba įkelkite bet kokį failą ir leiskite DI jį perskaityti.\n\n3. Atverkite **žaidėją** ir atlikite vertinimą. DI įvertina jį pagal šešis ramsčius: puolimas, gynyba, fizika, neapčiuopiami dalykai, išplėstinė analizė ir strateginis tinkamumas, su pagrindimu prie kiekvieno įvertinimo.\n\n4. Sudarykite paketą **Team Eval/Packet**. Įtraukite vaizdo įrašą, fiksuotų rungtynių statistiką ir savo skautavimo pastabas apie varžovą, ir DI parašys iš viso to vieną ataskaitą. Pasirinkite daugiau nei vieną ataskaitos tipą ir jis sujungs juos į vieną dokumentą.\n\n**Ask BloomPrint** skaito jūsų pačių duomenis, atsako į klausimus ir padeda darbe:\n\n- Kurie žaidėjai dabar įvertinti geriausiai?\n- Su kuriais varžovais mums buvo sunku?\n- Išnagrinėk kitą mūsų varžovą\n- Parenk trenerio ataskaitą mano komandai\n- Kaip importuoti sudėtį?'),
    "ar": ('مرحبًا بك في BloomPrint',
           'يكتب BloomPrint تقييمات اللاعبين وتقارير الاستكشاف وتقارير المباريات وبرامج التدريب انطلاقًا من قائمتك ومن المباريات التي تسجّلها.\n\nمن أين تبدأ.\n\n١. املأ **النظام والفلسفة** في ملفك الشخصي. صف ما تلعبه وما تبحث عنه في اللاعب. يطبّق الذكاء الاصطناعي ذلك على كل تقرير وكل برنامج تدريبي يكتبه، فكلما أضفت أكثر، اقترب النص من نظامك ومن مدى ملاءمة اللاعب لفريقك.\n\n٢. أنشئ فريقًا وأضف **قائمتك**. اكتب اللاعبين واحدًا تلو الآخر أو ارفع أي ملف ودع الذكاء الاصطناعي يقرأه.\n\n٣. افتح **لاعبًا** وأجرِ تقييمًا. يقيّمه الذكاء الاصطناعي على الركائز الست: الهجوم والدفاع والبدني وغير الملموس والتحليل المتقدم والملاءمة التكتيكية، مع سبب كل درجة.\n\n٤. ابنِ حزمة في **Team Eval/Packet**. أضف الفيديو وإحصاءات مباراة سجّلتها وملاحظاتك عن الخصم، وسيكتب الذكاء الاصطناعي تقريرًا واحدًا من كل ذلك. اختر أكثر من نوع تقرير وسيدمجها في مستند واحد.\n\nيقرأ **Ask BloomPrint** بياناتك للإجابة عن الأسئلة ويساعدك في العمل:\n\n- من هم أعلى لاعبيّ تقييمًا الآن؟\n- مع أي خصوم واجهنا صعوبة؟\n- استكشف خصمنا القادم\n- أعدّ تقرير مدرب لفريقي\n- كيف أستورد قائمة؟'),
    "he": ('ברוך הבא ל־BloomPrint',
           'BloomPrint כותב הערכות שחקנים, דוחות סקאוטינג, דוחות משחק ותוכניות אימון מתוך הסגל שלכם ומהמשחקים שאתם מתעדים.\n\nמאיפה מתחילים.\n\n1. מלאו **שיטה ופילוסופיה** בפרופיל. תארו במה אתם משחקים ומה חשוב לכם בשחקן. הבינה המלאכותית מיישמת את זה בכל דוח ובכל תוכנית אימון שהיא כותבת, ולכן ככל שתכתבו יותר, כך הטקסט צמוד יותר לשיטה שלכם ולאופן שבו שחקן משתלב בקבוצה.\n\n2. צרו קבוצה והוסיפו את **הסגל**. הקלידו שחקנים אחד אחד או העלו כל קובץ ותנו לבינה המלאכותית לקרוא אותו.\n\n3. פתחו **שחקן** ובצעו הערכה. הבינה המלאכותית מדרגת אותו בשישה עמודים: התקפה, הגנה, פיזיות, בלתי מדיד, ניתוח מתקדם והתאמה טקטית, עם ההנמקה מאחורי כל ציון.\n\n4. בנו חבילה ב-**Team Eval/Packet**. הוסיפו וידאו, נתונים ממשחק שתיעדתם והערות סקאוטינג על היריב, והבינה המלאכותית תכתוב מכל זה דוח אחד. בחרו יותר מסוג דוח אחד והיא תאחד אותם למסמך אחד.\n\n**Ask BloomPrint** קורא את הנתונים שלכם, עונה על שאלות ועוזר בעבודה:\n\n- מי השחקנים עם הציונים הגבוהים ביותר כרגע?\n- מול אילו יריבות התקשינו?\n- נתח את היריבה הבאה שלנו\n- הכן דוח מאמן לקבוצה שלי\n- איך מייבאים סגל?'),
    "hi": ('BloomPrint में आपका स्वागत है',
           'BloomPrint आपकी टीम सूची और आपके दर्ज किए गए मैचों से खिलाड़ी मूल्यांकन, स्काउटिंग रिपोर्ट, मैच रिपोर्ट और प्रशिक्षण कार्यक्रम लिखता है।\n\nकहाँ से शुरू करें।\n\n1. अपनी प्रोफ़ाइल में **सिस्टम और फ़िलॉसफ़ी** भरें। बताइए कि आप क्या खेलते हैं और खिलाड़ी में क्या देखते हैं। AI इसे हर रिपोर्ट और हर प्रशिक्षण कार्यक्रम पर लागू करता है, इसलिए जितना ज़्यादा लिखेंगे, लेखन उतना ही आपके सिस्टम और खिलाड़ी की टीम में फ़िट के करीब रहेगा।\n\n2. एक टीम बनाइए और अपनी **टीम सूची** जोड़िए। खिलाड़ियों को एक-एक करके लिखिए, या कोई भी फ़ाइल अपलोड कीजिए और AI को पढ़ने दीजिए।\n\n3. किसी **खिलाड़ी** को खोलकर मूल्यांकन कीजिए। AI उसे छह स्तंभों पर आँकता है: आक्रमण, रक्षा, शारीरिक, अमूर्त गुण, उन्नत विश्लेषण और रणनीतिक फ़िट, हर अंक के पीछे का कारण सहित।\n\n4. **Team Eval/Packet** में एक पैकेट बनाइए। फ़ुटेज, किसी दर्ज मैच के आँकड़े और प्रतिद्वंद्वी पर अपने स्काउटिंग नोट्स डालिए, और AI इन सबसे एक रिपोर्ट लिखेगा। एक से ज़्यादा रिपोर्ट प्रकार चुनिए और वह उन्हें एक दस्तावेज़ में जोड़ देगा।\n\n**Ask BloomPrint** आपके अपने डेटा से सवालों के जवाब देता है और काम में मदद करता है:\n\n- अभी मेरे सबसे ऊँचे अंक वाले खिलाड़ी कौन हैं?\n- किन प्रतिद्वंद्वियों के ख़िलाफ़ हमें दिक्कत हुई?\n- हमारे अगले प्रतिद्वंद्वी को स्काउट करो\n- मेरी टीम के लिए कोचिंग रिपोर्ट बनाओ\n- टीम सूची कैसे इम्पोर्ट करूँ?'),
    "ka": ('კეთილი იყოს თქვენი მობრძანება BloomPrint-ზე',
           'BloomPrint წერს მოთამაშეთა შეფასებებს, სკაუტინგის ანგარიშებს, მატჩის ანგარიშებს და სავარჯიშო პროგრამებს თქვენი შემადგენლობისა და იმ მატჩების მიხედვით, რომლებსაც აღრიცხავთ.\n\nსაიდან დაიწყოთ.\n\n1. შეავსეთ **სისტემა და ფილოსოფია** თქვენს პროფილში. აღწერეთ, რას თამაშობთ და რას აფასებთ მოთამაშეში. AI ამას იყენებს ყოველ ანგარიშსა და ყოველ სავარჯიშო პროგრამაში, ამიტომ რაც მეტს ჩაწერთ, მით უფრო ახლოს იქნება ტექსტი თქვენს სისტემასთან და იმასთან, როგორ ჯდება მოთამაშე გუნდში.\n\n2. შექმენით გუნდი და დაამატეთ **შემადგენლობა**. ჩაწერეთ მოთამაშეები სათითაოდ, ან ატვირთეთ ნებისმიერი ფაილი და მიეცით AI-ს წაკითხვის საშუალება.\n\n3. გახსენით **მოთამაშე** და ჩაატარეთ შეფასება. AI აფასებს მას ექვსი საყრდენით: შეტევა, დაცვა, ფიზიკა, არამატერიალური, გაღრმავებული ანალიზი და სტრატეგიული შესაბამისობა, თითოეული ქულის დასაბუთებით.\n\n4. ააწყვეთ პაკეტი **Team Eval/Packet**-ში. დაამატეთ ვიდეო, აღრიცხული მატჩის სტატისტიკა და თქვენი სკაუტინგის ჩანაწერები მოწინააღმდეგეზე, და AI დაწერს ამ ყველაფრიდან ერთ ანგარიშს. აირჩიეთ რამდენიმე ტიპი და ის გააერთიანებს მათ ერთ დოკუმენტში.\n\n**Ask BloomPrint** კითხულობს თქვენს მონაცემებს, პასუხობს კითხვებს და გეხმარებათ საქმეში:\n\n- ვინ არიან ახლა ჩემი ყველაზე მაღალშეფასებული მოთამაშეები?\n- რომელ მოწინააღმდეგეებთან გაგვიჭირდა?\n- შეისწავლე ჩვენი შემდეგი მოწინააღმდეგე\n- შექმენი მწვრთნელის ანგარიში ჩემი გუნდისთვის\n- როგორ შემოვიტანო შემადგენლობა?'),
    "ja": ('BloomPrint へようこそ',
           'BloomPrint は、あなたのロスターと記録した試合から、選手評価、スカウティングレポート、試合レポート、トレーニングプログラムを書きます。\n\nはじめに行うこと。\n\n1. プロフィールの **システムと哲学** を記入します。どんなバスケットをするか、選手の何を重視するかを書いてください。AI は書くすべてのレポートとトレーニングプログラムにこれを適用します。書き込むほど、文章はあなたのシステムと、その選手がチームにどう合うかに寄っていきます。\n\n2. チームを作り、**ロスター** を追加します。選手を一人ずつ入力するか、どんなファイルでもアップロードして AI に読ませてください。\n\n3. **選手** を開いて評価を実行します。AI は六つの柱、オフェンス、ディフェンス、フィジカル、無形の要素、アドバンスト、戦術的フィットで採点し、それぞれの根拠も示します。\n\n4. **Team Eval/Packet** でパケットを作ります。映像、記録した試合のスタッツ、相手についてのスカウティングメモをまとめると、AI がそのすべてから一本のレポートを書きます。レポートの種類を複数選べば、一つの文書にまとめます。\n\n**Ask BloomPrint** はあなた自身のデータを読んで質問に答え、作業を手伝います。\n\n- 今いちばん評価の高い選手は誰か\n- どの相手に苦戦したか\n- 次の対戦相手をスカウトして\n- チームのコーチングレポートを作って\n- ロスターの取り込み方は'),
    "ko": ('BloomPrint에 오신 것을 환영합니다',
           'BloomPrint은 로스터와 기록한 경기를 바탕으로 선수 평가, 스카우팅 리포트, 경기 리포트, 훈련 프로그램을 작성합니다.\n\n어디서 시작할지.\n\n1. 프로필의 **시스템 및 철학**을 채우세요. 어떤 농구를 하는지, 선수에게서 무엇을 보는지 적으면 됩니다. AI는 작성하는 모든 리포트와 훈련 프로그램에 이를 적용하므로, 많이 적을수록 글이 당신의 시스템과 선수의 팀 적합성에 더 가까워집니다.\n\n2. 팀을 만들고 **로스터**를 추가하세요. 선수를 하나씩 입력하거나, 아무 파일이나 올려 AI가 읽게 하면 됩니다.\n\n3. **선수**를 열어 평가를 실행하세요. AI가 여섯 기둥, 공격, 수비, 신체, 무형의 요소, 고급 분석, 전술적 적합성으로 평가하고 각 점수의 근거를 함께 제시합니다.\n\n4. **Team Eval/Packet**에서 패킷을 만드세요. 영상, 기록한 경기의 스탯, 상대에 대한 스카우팅 메모를 모으면 AI가 그 전부에서 하나의 리포트를 씁니다. 리포트 유형을 여러 개 고르면 하나의 문서로 합쳐 줍니다.\n\n**Ask BloomPrint**는 당신의 데이터를 읽어 질문에 답하고 작업을 돕습니다:\n\n- 지금 가장 평가가 높은 선수는 누구인가\n- 어떤 상대에게 고전했나\n- 다음 상대를 스카우팅해 줘\n- 우리 팀 코칭 리포트를 만들어 줘\n- 로스터는 어떻게 가져오나\n'),
    "zh": ('欢迎使用 BloomPrint',
           'BloomPrint 依据你的球员名单和你记录的比赛，撰写球员评估、球探报告、比赛报告和训练计划。\n\n从哪里开始。\n\n1. 在个人资料里填写 **体系与理念**。写下你打什么、你看重球员的哪些方面。AI 会把它应用到写出的每一份报告和每一份训练计划上，你写得越多，文字就越贴近你的体系以及球员与球队的契合度。\n\n2. 建立球队并添加 **名单**。逐个输入球员，或上传任意文件让 AI 读取。\n\n3. 打开一名 **球员** 做一次评估。AI 会在六大支柱上打分：进攻、防守、身体、无形因素、进阶分析和战术契合，并给出每一项分数的依据。\n\n4. 在 **Team Eval/Packet** 里搭建一个资料包。放入影像、你记录的某场比赛的数据以及你对对手的球探笔记，AI 会据此写出一份完整报告。选择多种报告类型，它会合并成一份文件。\n\n**Ask BloomPrint** 读取你自己的数据来回答问题，并协助你完成工作：\n\n- 现在评分最高的球员是谁？\n- 我们对上哪些对手时比较吃力？\n- 球探一下我们的下一个对手\n- 为我的球队写一份教练报告\n- 名单该怎么导入？'),
    "tl": ('Maligayang pagdating sa BloomPrint',
           'Sumusulat ang BloomPrint ng player evaluation, scouting report, game report at training program mula sa iyong roster at sa mga larong tine-track mo.\n\nSaan magsisimula.\n\n1. Punan ang **System at Philosophy** sa iyong profile. Ilarawan ang sistema mo at kung ano ang hinahanap mo sa isang manlalaro. Inilalapat ito ng AI sa bawat report at bawat training program na isinusulat nito, kaya habang mas marami kang ilalagay, mas malapit ang isinusulat sa sistema mo at sa kung paano kasya ang manlalaro sa koponan.\n\n2. Gumawa ng koponan at idagdag ang iyong **roster**. I-type ang mga manlalaro isa-isa, o mag-upload ng kahit anong file at hayaang basahin ito ng AI.\n\n3. Buksan ang isang **manlalaro** at magpatakbo ng evaluation. Ginagradohan siya ng AI sa anim na haligi: opensa, depensa, pisikal, intangibles, advanced at strategic fit, kasama ang dahilan sa likod ng bawat grado.\n\n4. Bumuo ng packet sa **Team Eval/Packet**. Isama ang film, ang stats ng laro na tinrack mo at ang iyong scouting notes tungkol sa kalaban, at susulat ang AI ng iisang report mula sa lahat ng iyon. Pumili ng higit sa isang uri ng report at pagsasamahin niya ang mga ito sa isang dokumento.\n\nBinabasa ng **Ask BloomPrint** ang sarili mong datos para sumagot ng tanong, at tumutulong ito sa trabaho:\n\n- Sino ang pinakamataas ang grado kong mga manlalaro ngayon?\n- Kanino kaming kalaban nahirapan?\n- I-scout ang susunod naming kalaban\n- Gumawa ng coaching report para sa koponan ko\n- Paano mag-import ng roster?'),
}


EVENTS["signup_player"] = {
    "en": ("Welcome to BloomPrint",
           "Your coaching staff can share reports and training programs with you here. Both are written by BloomPrint AI from your coach's own inputs and criteria, so what you read is measured against how they see the game.\n\nWhere to start.\n\n1. Link your account to your coach or trainer. They approve the request, and after that anything they send reaches you.\n\n2. A report arrives under **Reports** as soon as a coach or trainer sends you one. Open it to read what they wrote about you.\n\n3. Under **Training**, a program you have been sent is broken into a checklist by our AI. Tick items off as you go.\n\nComment on any report or program to ask a question, and your coach can answer in the same place."),
    "es": ('Bienvenido a BloomPrint',
           'Tu cuerpo técnico puede compartir informes y programas de entrenamiento contigo aquí. Ambos los escribe BloomPrint AI a partir de los criterios de tu entrenador, así que lo que lees se mide según cómo ve él el juego.\n\nPor dónde empezar.\n\n1. Vincula tu cuenta con tu entrenador o preparador. Él aprueba la solicitud y, a partir de ahí, todo lo que te envíe te llega.\n\n2. Un informe aparece en **Informes** en cuanto un entrenador o preparador te envía uno. Ábrelo para leer lo que escribió sobre ti.\n\n3. En **Entrenamiento**, un programa que te hayan enviado lo desglosa nuestra IA en una lista de tareas. Ve marcándolas a medida que avanzas.\n\nComenta cualquier informe o programa para hacer una pregunta, y tu entrenador puede responderte ahí mismo.'),
    "fr": ('Bienvenue sur BloomPrint',
           "Votre staff peut partager des rapports et des programmes d'entraînement avec vous ici. Les deux sont rédigés par BloomPrint AI à partir des critères de votre entraîneur, donc ce que vous lisez est jugé selon sa façon de voir le jeu.\n\nPar où commencer.\n\n1. Reliez votre compte à votre entraîneur ou préparateur. Il approuve la demande, et ensuite tout ce qu'il envoie vous parvient.\n\n2. Un rapport arrive dans **Rapports** dès qu'un entraîneur ou préparateur vous en envoie un. Ouvrez-le pour lire ce qu'il a écrit sur vous.\n\n3. Dans **Entraînement**, un programme qu'on vous a envoyé est découpé par notre IA en une liste à cocher. Cochez au fur et à mesure.\n\nCommentez n'importe quel rapport ou programme pour poser une question, et votre entraîneur peut y répondre au même endroit."),
    "pt": ('Bem-vindo ao BloomPrint',
           'A sua equipa técnica pode partilhar relatórios e programas de treino consigo aqui. Ambos são escritos pela BloomPrint AI a partir dos critérios do seu treinador, por isso o que lê é medido pela forma como ele vê o jogo.\n\nPor onde começar.\n\n1. Ligue a sua conta ao seu treinador ou preparador. Ele aprova o pedido e, a partir daí, tudo o que enviar chega até si.\n\n2. Um relatório aparece em **Relatórios** assim que um treinador ou preparador lhe envia um. Abra-o para ler o que escreveu sobre si.\n\n3. Em **Treino**, um programa que lhe tenham enviado é dividido pela nossa IA numa lista de tarefas. Vá marcando à medida que avança.\n\nComente qualquer relatório ou programa para fazer uma pergunta, e o seu treinador pode responder no mesmo sítio.'),
    "it": ('Benvenuto su BloomPrint',
           'Il tuo staff può condividere report e programmi di allenamento con te qui. Entrambi sono scritti da BloomPrint AI a partire dai criteri del tuo allenatore, quindi quello che leggi è misurato su come vede lui il gioco.\n\nDa dove iniziare.\n\n1. Collega il tuo account al tuo allenatore o preparatore. Lui approva la richiesta e da quel momento tutto ciò che ti manda ti arriva.\n\n2. Un report compare in **Report** appena un allenatore o preparatore te ne manda uno. Aprilo per leggere cosa ha scritto su di te.\n\n3. In **Allenamento**, un programma che ti è stato mandato viene diviso dalla nostra IA in una lista da spuntare. Spunta le voci man mano.\n\nCommenta qualsiasi report o programma per fare una domanda, e il tuo allenatore può risponderti lì.'),
    "de": ('Willkommen bei BloomPrint',
           'Dein Trainerteam kann hier Berichte und Trainingsprogramme mit dir teilen. Beides schreibt BloomPrint AI aus den Vorgaben deines Trainers, sodass das, was du liest, an seiner Sicht auf das Spiel gemessen wird.\n\nWo du anfängst.\n\n1. Verbinde dein Konto mit deinem Trainer oder Athletiktrainer. Er bestätigt die Anfrage, und danach kommt alles bei dir an, was er schickt.\n\n2. Ein Bericht erscheint unter **Berichte**, sobald ein Trainer dir einen schickt. Öffne ihn und lies, was über dich geschrieben wurde.\n\n3. Unter **Training** wird ein Programm, das du bekommen hast, von unserer KI in eine Checkliste zerlegt. Hak sie ab, während du sie durchgehst.\n\nKommentiere jeden Bericht oder jedes Programm, um eine Frage zu stellen: dein Trainer kann an derselben Stelle antworten.'),
    "nl": ('Welkom bij BloomPrint',
           "Je staf kan hier rapporten en trainingsprogramma's met je delen. Beide worden geschreven door BloomPrint AI vanuit de criteria van je coach, dus wat je leest wordt gemeten aan hoe hij het spel ziet.\n\nWaar te beginnen.\n\n1. Koppel je account aan je coach of trainer. Hij keurt het verzoek goed, en daarna bereikt alles wat hij stuurt jou.\n\n2. Een rapport verschijnt onder **Rapporten** zodra een coach of trainer je er een stuurt. Open het om te lezen wat er over je geschreven is.\n\n3. Onder **Training** wordt een programma dat je hebt gekregen door onze AI opgedeeld in een checklist. Vink af terwijl je bezig bent.\n\nReageer op elk rapport of programma om een vraag te stellen, en je coach kan op dezelfde plek antwoorden."),
    "sv": ('Välkommen till BloomPrint',
           'Din tränarstab kan dela rapporter och träningsprogram med dig här. Båda skrivs av BloomPrint AI utifrån din tränares egna kriterier, så det du läser mäts mot hur hen ser på spelet.\n\nVar du börjar.\n\n1. Koppla ditt konto till din tränare. Hen godkänner förfrågan, och därefter når allt hen skickar fram till dig.\n\n2. En rapport dyker upp under **Rapporter** så snart en tränare skickar dig en. Öppna den och läs vad som skrivits om dig.\n\n3. Under **Träning** delar vår AI upp ett program du fått i en checklista. Bocka av allteftersom.\n\nKommentera vilken rapport eller vilket program som helst för att ställa en fråga, så kan din tränare svara på samma ställe.'),
    "pl": ('Witamy w BloomPrint',
           'Twój sztab może udostępniać Ci tutaj raporty i programy treningowe. Oba pisze BloomPrint AI na podstawie kryteriów Twojego trenera, więc to, co czytasz, mierzone jest jego spojrzeniem na grę.\n\nOd czego zacząć.\n\n1. Połącz konto ze swoim trenerem. Zatwierdzi prośbę i od tej pory wszystko, co wyśle, trafi do Ciebie.\n\n2. Raport pojawia się w **Raportach**, gdy tylko trener Ci go wyśle. Otwórz go i przeczytaj, co o Tobie napisał.\n\n3. W **Treningu** program, który dostałeś, nasza AI dzieli na listę zadań. Odhaczaj je w miarę postępów.\n\nSkomentuj dowolny raport lub program, żeby zadać pytanie, a trener odpowie w tym samym miejscu.'),
    "ru": ('Добро пожаловать в BloomPrint',
           'Ваш тренерский штаб может делиться с вами отчётами и тренировочными программами здесь. И то и другое пишет BloomPrint AI по критериям вашего тренера, поэтому прочитанное измеряется тем, как он видит игру.\n\nС чего начать.\n\n1. Свяжите аккаунт со своим тренером. Он подтвердит запрос, и с этого момента всё, что он отправит, будет доходить до вас.\n\n2. Отчёт появляется в разделе **Отчёты**, как только тренер вам его отправит. Откройте и прочитайте, что о вас написано.\n\n3. В разделе **Тренировки** присланную программу наш ИИ разбивает в список задач. Отмечайте их по ходу.\n\nОставьте комментарий к любому отчёту или программе, чтобы задать вопрос, и тренер ответит там же.'),
    "uk": ('Ласкаво просимо до BloomPrint',
           "Ваш тренерський штаб може ділитися з вами звітами та тренувальними програмами тут. І те й інше пише BloomPrint AI за критеріями вашого тренера, тож прочитане вимірюється тим, як він бачить гру.\n\nЗ чого почати.\n\n1. Прив'яжіть акаунт до свого тренера. Він підтвердить запит, і відтоді все, що він надішле, доходитиме до вас.\n\n2. Звіт з'являється в розділі **Звіти**, щойно тренер вам його надішле. Відкрийте і прочитайте, що про вас написано.\n\n3. У розділі **Тренування** надіслану програму наш ШІ розбиває на список завдань. Позначайте їх у міру виконання.\n\nЗалиште коментар до будь-якого звіту чи програми, щоб поставити запитання, і тренер відповість там само."),
    "sr": ('Добро дошли у BloomPrint',
           'Ваш стручни штаб може да дели извештаје и тренажне програме са вама овде. Оба пише BloomPrint AI на основу критеријума вашег тренера, па се оно што читате мери његовим погледом на игру.\n\nОдакле почети.\n\n1. Повежите налог са својим тренером. Он одобрава захтев и од тада вам стиже све што пошаље.\n\n2. Извештај се појављује у одељку **Извештаји** чим вам га тренер пошаље. Отворите га и прочитајте шта је написао о вама.\n\n3. У одељку **Тренинг** послати програм наша ВИ дели у листу задатака. Штиклирајте их како напредујете.\n\nОставите коментар на било који извештај или програм да поставите питање, а тренер може да одговори на истом месту.'),
    "hr": ('Dobrodošli u BloomPrint',
           'Vaš stručni stožer može ovdje dijeliti izvještaje i programe treninga s vama. Oboje piše BloomPrint AI na temelju kriterija vašeg trenera, pa se ono što čitate mjeri njegovim pogledom na igru.\n\nOdakle početi.\n\n1. Povežite račun sa svojim trenerom. On odobrava zahtjev i od tada vam stiže sve što pošalje.\n\n2. Izvještaj se pojavljuje u odjeljku **Izvještaji** čim vam ga trener pošalje. Otvorite ga i pročitajte što je napisao o vama.\n\n3. U odjeljku **Trening** poslani program naša UI dijeli u listu zadataka. Označavajte ih kako napredujete.\n\nOstavite komentar na bilo koji izvještaj ili program da postavite pitanje, a trener može odgovoriti na istom mjestu.'),
    "tr": ("BloomPrint'e hoş geldiniz",
           'Teknik ekibiniz raporları ve antrenman programlarını burada sizinle paylaşabilir. İkisini de BloomPrint AI, antrenörünüzün kendi ölçütlerinden yazar; yani okuduğunuz şey onun oyuna bakışına göre değerlendirilir.\n\nNereden başlamalı.\n\n1. Hesabınızı antrenörünüze bağlayın. İsteği onaylar, sonrasında gönderdiği her şey size ulaşır.\n\n2. Bir antrenör size rapor gönderdiği anda **Raporlar** altında görünür. Açın ve hakkınızda yazdıklarını okuyun.\n\n3. **Antrenman** altında, size gönderilen program yapay zekâmız tarafından bir kontrol listesine ayrılır. İlerledikçe işaretleyin.\n\nSoru sormak için herhangi bir rapora ya da programa yorum bırakın; antrenörünüz aynı yerde yanıtlayabilir.'),
    "ro": ('Bine ai venit pe BloomPrint',
           'Staff-ul tău poate împărtăși aici rapoarte și programe de antrenament cu tine. Ambele sunt scrise de BloomPrint AI pornind de la criteriile antrenorului tău, așa că ce citești este măsurat după felul în care vede el jocul.\n\nDe unde începi.\n\n1. Leagă-ți contul de antrenorul tău. El aprobă cererea, iar de atunci tot ce trimite ajunge la tine.\n\n2. Un raport apare la **Rapoarte** de îndată ce un antrenor îți trimite unul. Deschide-l și citește ce a scris despre tine.\n\n3. La **Antrenament**, un program pe care l-ai primit este împărțit de IA noastră într-o listă de bifat. Bifează pe măsură ce înaintezi.\n\nLasă un comentariu la orice raport sau program ca să pui o întrebare, iar antrenorul poate răspunde în același loc.'),
    "el": ('Καλώς ήρθες στο BloomPrint',
           'Το προπονητικό σας τιμ μπορεί να μοιράζεται εδώ αναφορές και προγράμματα προπόνησης μαζί σας. Και τα δύο τα γράφει το BloomPrint AI από τα κριτήρια του προπονητή σας, οπότε αυτό που διαβάζετε μετριέται με βάση το πώς βλέπει εκείνος το παιχνίδι.\n\nΑπό πού ξεκινάτε.\n\n1. Συνδέστε τον λογαριασμό σας με τον προπονητή σας. Εκείνος εγκρίνει το αίτημα και από εκεί και πέρα ό,τι στέλνει φτάνει σε εσάς.\n\n2. Μια αναφορά εμφανίζεται στις **Αναφορές** μόλις σας τη στείλει ένας προπονητής. Ανοίξτε την και διαβάστε τι έγραψε για εσάς.\n\n3. Στην **Προπόνηση**, ένα πρόγραμμα που σας έστειλαν το χωρίζει η ΤΝ μας σε λίστα εργασιών. Τσεκάρετέ τις καθώς προχωράτε.\n\nΣχολιάστε οποιαδήποτε αναφορά ή πρόγραμμα για να κάνετε μια ερώτηση, και ο προπονητής σας μπορεί να απαντήσει στο ίδιο σημείο.'),
    "lt": ('Sveiki atvykę į BloomPrint',
           'Jūsų treneriai gali čia dalintis su jumis ataskaitomis ir treniruočių programomis. Abi rašo BloomPrint AI pagal jūsų trenerio kriterijus, tad tai, ką skaitote, vertinama pagal tai, kaip jis mato žaidimą.\n\nNuo ko pradėti.\n\n1. Susiekite paskyrą su savo treneriu. Jis patvirtins prašymą, ir nuo tada viskas, ką atsiųs, pasieks jus.\n\n2. Ataskaita atsiranda skiltyje **Ataskaitos**, vos treneris ją atsiunčia. Atverkite ir perskaitykite, ką apie jus parašė.\n\n3. Skiltyje **Treniruotės** atsiųstą programą mūsų DI suskaido į užduočių sąrašą. Žymėkite jas eidami per programą.\n\nPalikite komentarą po bet kuria ataskaita ar programa, kad užduotumėte klausimą, ir treneris galės atsakyti toje pačioje vietoje.'),
    "ar": ('مرحبًا بك في BloomPrint',
           'يمكن لطاقمك التدريبي مشاركة التقارير وبرامج التدريب معك هنا. كلاهما يكتبه BloomPrint AI انطلاقًا من معايير مدربك، فما تقرأه يُقاس بطريقة رؤيته للعبة.\n\nمن أين تبدأ.\n\n١. اربط حسابك بمدربك. سيوافق على الطلب، وبعدها يصلك كل ما يرسله.\n\n٢. يظهر التقرير في **التقارير** بمجرد أن يرسله لك مدرب. افتحه واقرأ ما كتبه عنك.\n\n٣. في **التدريب**، يقسّم ذكاؤنا الاصطناعي البرنامج المُرسل إليك إلى قائمة مهام. علّم عليها كلما تقدمت.\n\nاترك تعليقًا على أي تقرير أو برنامج لتطرح سؤالًا، ويستطيع مدربك الرد في المكان نفسه.'),
    "he": ('ברוך הבא ל־BloomPrint',
           'הצוות המקצועי יכול לשתף אתכם כאן בדוחות ובתוכניות אימון. את שניהם כותב BloomPrint AI מתוך הקריטריונים של המאמן שלכם, כך שמה שאתם קוראים נמדד לפי איך שהוא רואה את המשחק.\n\nמאיפה מתחילים.\n\n1. קשרו את החשבון למאמן שלכם. הוא יאשר את הבקשה, ומאותו רגע כל מה שישלח יגיע אליכם.\n\n2. דוח מופיע תחת **דוחות** ברגע שמאמן שולח לכם אחד. פתחו וקראו מה נכתב עליכם.\n\n3. תחת **אימון**, תוכנית שנשלחה אליכם מפורקת על ידי ה-AI שלנו לרשימת משימות. סמנו אותן תוך כדי.\n\nהגיבו על כל דוח או תוכנית כדי לשאול שאלה, והמאמן יוכל לענות באותו מקום.'),
    "hi": ('BloomPrint में आपका स्वागत है',
           'आपका कोचिंग स्टाफ़ यहाँ आपके साथ रिपोर्ट और प्रशिक्षण कार्यक्रम साझा कर सकता है। दोनों BloomPrint AI आपके कोच के अपने मानदंडों से लिखता है, इसलिए जो आप पढ़ते हैं वह इस बात से आँका जाता है कि वे खेल को कैसे देखते हैं।\n\nकहाँ से शुरू करें।\n\n1. अपने खाते को अपने कोच या ट्रेनर से जोड़िए। वे अनुरोध मंज़ूर करेंगे, और उसके बाद वे जो भी भेजेंगे आप तक पहुँचेगा।\n\n2. जैसे ही कोई कोच आपको रिपोर्ट भेजता है, वह **रिपोर्ट** में आ जाती है। खोलकर पढ़िए कि उन्होंने आपके बारे में क्या लिखा।\n\n3. **प्रशिक्षण** में, आपको भेजे गए कार्यक्रम को हमारा AI एक चेकलिस्ट में बाँट देता है। आगे बढ़ते हुए उन्हें टिक करते जाइए।\n\nसवाल पूछने के लिए किसी भी रिपोर्ट या कार्यक्रम पर टिप्पणी कीजिए, और आपके कोच वहीं जवाब दे सकते हैं।'),
    "ka": ('კეთილი იყოს თქვენი მობრძანება BloomPrint-ზე',
           'თქვენს სამწვრთნელო შტაბს შეუძლია აქ გაგიზიაროთ ანგარიშები და სავარჯიშო პროგრამები. ორივეს წერს BloomPrint AI თქვენი მწვრთნელის კრიტერიუმებიდან, ამიტომ ის, რასაც კითხულობთ, იზომება იმით, როგორ ხედავს ის თამაშს.\n\nსაიდან დაიწყოთ.\n\n1. დააკავშირეთ ანგარიში თქვენს მწვრთნელს. ის დაადასტურებს მოთხოვნას და ამის შემდეგ ყველაფერი, რასაც გამოგიგზავნით, მოგივათ.\n\n2. ანგარიში ჩნდება განყოფილებაში **ანგარიშები**, როგორც კი მწვრთნელი გამოგიგზავნით. გახსენით და წაიკითხეთ, რა დაწერა თქვენზე.\n\n3. განყოფილებაში **ვარჯიში** გამოგზავნილ პროგრამას ჩვენი AI ყოფს დავალებების სიად. მონიშნეთ ისინი წინსვლისას.\n\nდატოვეთ კომენტარი ნებისმიერ ანგარიშზე ან პროგრამაზე კითხვის დასასმელად, და მწვრთნელი იმავე ადგილას გიპასუხებთ.'),
    "ja": ('BloomPrint へようこそ',
           'コーチングスタッフは、ここであなたにレポートやトレーニングプログラムを共有できます。どちらも BloomPrint AI がコーチ自身の基準から書くので、読む内容はそのコーチのバスケットの見方で測られます。\n\nはじめに行うこと。\n\n1. アカウントをコーチまたはトレーナーと連携します。相手が承認すると、それ以降に送られたものが届くようになります。\n\n2. コーチがレポートを送ると **レポート** に届きます。開いて、あなたについて書かれた内容を読んでください。\n\n3. **トレーニング** では、送られたプログラムを当社の AI がチェックリストに分解します。進めながらチェックを入れてください。\n\nどのレポートやプログラムにもコメントで質問でき、コーチは同じ場所で返信できます。'),
    "ko": ('BloomPrint에 오신 것을 환영합니다',
           '코칭스태프가 여기서 리포트와 훈련 프로그램을 공유할 수 있습니다. 둘 다 BloomPrint AI가 코치의 기준을 바탕으로 작성하므로, 읽는 내용은 그 코치가 농구를 보는 방식으로 평가됩니다.\n\n어디서 시작할지.\n\n1. 계정을 코치나 트레이너와 연결하세요. 상대가 요청을 승인하면 그 뒤로 보내는 모든 것이 도착합니다.\n\n2. 코치가 리포트를 보내면 **리포트**에 들어옵니다. 열어서 당신에 대해 쓴 내용을 읽어 보세요.\n\n3. **훈련**에서는 받은 프로그램을 저희 AI가 체크리스트로 나눕니다. 진행하면서 하나씩 체크하세요.\n\n어떤 리포트나 프로그램에도 댓글로 질문할 수 있고, 코치는 같은 자리에서 답할 수 있습니다.'),
    "zh": ('欢迎使用 BloomPrint',
           '教练组可以在这里与你分享报告和训练计划。两者都由 BloomPrint AI 根据你教练自己的标准撰写，因此你读到的内容是按他看待比赛的方式来衡量的。\n\n从哪里开始。\n\n1. 把账户与你的教练或体能师关联。对方通过请求后，之后他发送的一切都会送到你这里。\n\n2. 教练一发送报告，它就会出现在 **报告** 里。打开来读他写了你什么。\n\n3. 在 **训练** 里，别人发给你的计划会由我们的 AI 拆成一份清单。边做边勾。\n\n在任何报告或计划下留言提问，教练可以在同一处回复你。'),
    "tl": ('Maligayang pagdating sa BloomPrint',
           'Puwedeng magbahagi sa iyo rito ng report at training program ang coaching staff mo. Parehong isinusulat ng BloomPrint AI mula sa sariling pamantayan ng coach mo, kaya ang binabasa mo ay sinusukat sa kung paano niya tinitingnan ang laro.\n\nSaan magsisimula.\n\n1. Iugnay ang account mo sa coach o trainer mo. Aaprubahan niya ang request, at pagkatapos noon ay makakarating sa iyo ang lahat ng ipapadala niya.\n\n2. Lalabas ang report sa **Reports** sa oras na padalhan ka ng coach. Buksan mo at basahin ang isinulat niya tungkol sa iyo.\n\n3. Sa **Training**, hinahati ng AI namin ang programang ipinadala sa iyo bilang checklist. Tsekan mo habang tinatapos mo ang mga ito.\n\nMag-comment sa kahit anong report o program para magtanong, at makakasagot ang coach mo sa parehong lugar.'),
}


EVENTS["email_changed"] = {
    "en": ("Your BloomPrint email was changed",
           "The email on your account is now {email}. If this wasn't you, contact us straight away."),
    "es": ("Se ha cambiado tu correo de BloomPrint",
           "El correo de tu cuenta ahora es {email}. Si no has sido tú, contáctanos de inmediato."),
    "fr": ("Votre adresse e-mail BloomPrint a changé",
           "L'adresse de votre compte est désormais {email}. Si ce n'était pas vous, contactez-nous immédiatement."),
    "pt": ("O seu email do BloomPrint foi alterado",
           "O email da sua conta é agora {email}. Se não foi você, contacte-nos de imediato."),
    "it": ("La tua email BloomPrint è cambiata",
           "L'email del tuo account ora è {email}. Se non sei stato tu, contattaci subito."),
    "de": ("Deine BloomPrint-E-Mail wurde geändert",
           "Die E-Mail deines Kontos ist jetzt {email}. Falls du das nicht warst, melde dich sofort bei uns."),
    "nl": ("Je BloomPrint-e-mailadres is gewijzigd",
           "Het e-mailadres van je account is nu {email}. Was jij dit niet? Neem direct contact met ons op."),
    "sv": ("Din BloomPrint-e-post har ändrats",
           "E-postadressen på ditt konto är nu {email}. Om det inte var du, kontakta oss direkt."),
    "pl": ("Zmieniono Twój adres e-mail w BloomPrint",
           "Adres e-mail Twojego konta to teraz {email}. Jeśli to nie Ty, skontaktuj się z nami natychmiast."),
    "ru": ("Ваш адрес почты в BloomPrint изменён",
           "Адрес вашей учётной записи теперь {email}. Если это были не вы, немедленно свяжитесь с нами."),
    "uk": ("Вашу адресу пошти в BloomPrint змінено",
           "Адреса вашого облікового запису тепер {email}. Якщо це були не ви, негайно зв'яжіться з нами."),
    "sr": ("Ваша BloomPrint адреса је промењена",
           "Адреса вашег налога је сада {email}. Ако то нисте били ви, одмах нас контактирајте."),
    "hr": ("Vaša BloomPrint adresa je promijenjena",
           "Adresa vašeg računa sada je {email}. Ako to niste bili vi, odmah nas kontaktirajte."),
    "tr": ("BloomPrint e-posta adresiniz değişti",
           "Hesabınızın e-posta adresi artık {email}. Bunu siz yapmadıysanız hemen bizimle iletişime geçin."),
    "ro": ("Adresa ta de email BloomPrint a fost schimbată",
           "Emailul contului tău este acum {email}. Dacă nu ai fost tu, contactează-ne imediat."),
    "el": ("Το email σου στο BloomPrint άλλαξε",
           "Το email του λογαριασμού σου είναι πλέον {email}. Αν δεν το έκανες εσύ, επικοινώνησε αμέσως μαζί μας."),
    "lt": ("Jūsų BloomPrint el. paštas pakeistas",
           "Jūsų paskyros el. paštas dabar yra {email}. Jei tai buvote ne jūs, nedelsdami susisiekite su mumis."),
    "ar": ("تم تغيير بريدك في BloomPrint",
           "بريد حسابك الآن هو {email}. إذا لم تكن أنت من قام بذلك، تواصل معنا فورًا."),
    "he": ("כתובת המייל שלך ב־BloomPrint שונתה",
           "כתובת המייל בחשבון שלך היא כעת {email}. אם זה לא היית אתה, צור איתנו קשר מיד."),
    "hi": ("आपका BloomPrint ईमेल बदल दिया गया",
           "आपके खाते का ईमेल अब {email} है। यदि यह आपने नहीं किया, तो तुरंत हमसे संपर्क करें।"),
    "ka": ("თქვენი BloomPrint-ის ელფოსტა შეიცვალა",
           "თქვენი ანგარიშის ელფოსტა ახლა არის {email}. თუ ეს თქვენ არ ყოფილხართ, დაუყოვნებლივ დაგვიკავშირდით."),
    "ja": ("BloomPrint のメールアドレスが変更されました",
           "アカウントのメールアドレスが {email} になりました。心当たりがない場合はすぐにご連絡ください。"),
    "ko": ("BloomPrint 이메일이 변경되었습니다",
           "계정 이메일이 {email}(으)로 변경되었습니다. 본인이 아니라면 즉시 문의해 주세요."),
    "zh": ("你的 BloomPrint 邮箱已更改",
           "你账号的邮箱现已改为 {email}。如果这不是你本人操作，请立即联系我们。"),
    "tl": ("Nabago ang BloomPrint email mo",
           "Ang email ng account mo ay {email} na. Kung hindi ikaw ang gumawa nito, agad kaming kontakin."),
}


EVENTS["password_reset"] = {
    "en": ('Reset your BloomPrint password',
           'Use the link below to choose a new password. It works once and expires in 24 hours. If you did not ask for this, nothing has changed and you can ignore this message.'),
    "es": ('Restablece tu contraseña de BloomPrint',
           'Usa el enlace de abajo para elegir una nueva contraseña. Funciona una sola vez y caduca en 24 horas. Si no lo has solicitado, no ha cambiado nada y puedes ignorar este mensaje.'),
    "fr": ('Réinitialisez votre mot de passe BloomPrint',
           "Utilisez le lien ci-dessous pour choisir un nouveau mot de passe. Il fonctionne une seule fois et expire dans 24 heures. Si vous n'êtes pas à l'origine de cette demande, rien n'a changé et vous pouvez ignorer ce message."),
    "pt": ('Redefina a sua palavra-passe do BloomPrint',
           'Use a ligação abaixo para escolher uma nova palavra-passe. Funciona uma vez e expira em 24 horas. Se não pediu isto, nada mudou e pode ignorar esta mensagem.'),
    "it": ('Reimposta la tua password BloomPrint',
           'Usa il link qui sotto per scegliere una nuova password. Funziona una volta sola e scade tra 24 ore. Se non hai richiesto tu questa operazione, nulla è cambiato e puoi ignorare questo messaggio.'),
    "de": ('Setze dein BloomPrint-Passwort zurück',
           'Über den Link unten kannst du ein neues Passwort wählen. Er funktioniert einmal und läuft in 24 Stunden ab. Wenn du das nicht angefordert hast, hat sich nichts geändert und du kannst diese Nachricht ignorieren.'),
    "nl": ('Stel je BloomPrint-wachtwoord opnieuw in',
           'Gebruik de link hieronder om een nieuw wachtwoord te kiezen. Hij werkt één keer en verloopt over 24 uur. Heb je dit niet aangevraagd, dan is er niets veranderd en kun je dit bericht negeren.'),
    "sv": ('Återställ ditt BloomPrint-lösenord',
           'Använd länken nedan för att välja ett nytt lösenord. Den fungerar en gång och slutar gälla om 24 timmar. Om du inte har begärt detta har ingenting ändrats och du kan bortse från meddelandet.'),
    "pl": ('Zresetuj hasło do BloomPrint',
           'Skorzystaj z poniższego linku, aby ustawić nowe hasło. Działa jeden raz i wygasa po 24 godzinach. Jeśli to nie Ty prosiłeś o zmianę, nic się nie zmieniło i możesz zignorować tę wiadomość.'),
    "ru": ('Сброс пароля BloomPrint',
           'Перейдите по ссылке ниже, чтобы задать новый пароль. Она сработает один раз и истечёт через 24 часа. Если вы этого не запрашивали, ничего не изменилось и письмо можно не читать.'),
    "uk": ('Скидання пароля BloomPrint',
           'Скористайтеся посиланням нижче, щоб задати новий пароль. Воно спрацює один раз і діє 24 години. Якщо ви цього не запитували, нічого не змінилося і лист можна проігнорувати.'),
    "sr": ('Ресетујте лозинку за BloomPrint',
           'Употребите везу испод да изаберете нову лозинку. Ради једном и истиче за 24 сата. Ако то нисте тражили, ништа се није променило и можете занемарити ову поруку.'),
    "hr": ('Poništite svoju BloomPrint lozinku',
           'Upotrijebite poveznicu ispod za odabir nove lozinke. Radi jednom i istječe za 24 sata. Ako to niste tražili, ništa se nije promijenilo i možete zanemariti ovu poruku.'),
    "tr": ('BloomPrint şifrenizi sıfırlayın',
           'Yeni bir şifre seçmek için aşağıdaki bağlantıyı kullanın. Bir kez çalışır ve 24 saat içinde geçerliliğini yitirir. Bunu siz istemediyseniz hiçbir şey değişmedi, bu mesajı yok sayabilirsiniz.'),
    "ro": ('Resetează-ți parola BloomPrint',
           'Folosește linkul de mai jos pentru a alege o parolă nouă. Funcționează o singură dată și expiră în 24 de ore. Dacă nu tu ai cerut asta, nu s-a schimbat nimic și poți ignora mesajul.'),
    "el": ('Επαναφορά του κωδικού σας στο BloomPrint',
           'Χρησιμοποιήστε τον παρακάτω σύνδεσμο για να επιλέξετε νέο κωδικό. Λειτουργεί μία φορά και λήγει σε 24 ώρες. Αν δεν το ζητήσατε εσείς, δεν άλλαξε τίποτα και μπορείτε να αγνοήσετε το μήνυμα.'),
    "lt": ('Atkurkite BloomPrint slaptažodį',
           'Nauju slaptažodžiu pasirinkti naudokite žemiau esančią nuorodą. Ji veikia vieną kartą ir nustoja galioti po 24 valandų. Jei to neprašėte, niekas nepasikeitė ir žinutę galite ignoruoti.'),
    "ar": ('إعادة تعيين كلمة مرور BloomPrint',
           'استخدم الرابط أدناه لاختيار كلمة مرور جديدة. يعمل مرة واحدة وتنتهي صلاحيته خلال ٢٤ ساعة. إذا لم تطلب ذلك، فلم يتغير شيء ويمكنك تجاهل هذه الرسالة.'),
    "he": ('איפוס הסיסמה שלך ב-BloomPrint',
           'השתמשו בקישור שלמטה כדי לבחור סיסמה חדשה. הוא פועל פעם אחת ופג תוך 24 שעות. אם לא ביקשתם זאת, שום דבר לא השתנה ואפשר להתעלם מההודעה.'),
    "hi": ('अपना BloomPrint पासवर्ड रीसेट करें',
           'नया पासवर्ड चुनने के लिए नीचे दिए गए लिंक का उपयोग करें। यह एक बार काम करता है और 24 घंटे में समाप्त हो जाता है। यदि आपने यह अनुरोध नहीं किया, तो कुछ नहीं बदला है और आप इस संदेश को अनदेखा कर सकते हैं।'),
    "ka": ('აღადგინეთ BloomPrint-ის პაროლი',
           'ახალი პაროლის ასარჩევად გამოიყენეთ ქვემოთ მოცემული ბმული. ის ერთხელ მუშაობს და 24 საათში იწურება. თუ ეს თქვენ არ მოგითხოვიათ, არაფერი შეცვლილა და შეგიძლიათ უგულებელყოთ ეს წერილი.'),
    "ja": ('BloomPrint のパスワードを再設定',
           '下のリンクから新しいパスワードを設定してください。リンクは一度だけ有効で、24時間で期限が切れます。心当たりがない場合、何も変更されていませんのでこのメールは無視してください。'),
    "ko": ('BloomPrint 비밀번호 재설정',
           '아래 링크에서 새 비밀번호를 설정하세요. 링크는 한 번만 사용할 수 있으며 24시간 후 만료됩니다. 요청하지 않으셨다면 변경된 것은 없으니 이 메일은 무시하셔도 됩니다.'),
    "zh": ('重置你的 BloomPrint 密码',
           '使用下方链接设置新密码。该链接仅可使用一次，24 小时后失效。如果这不是你发起的，账户没有任何变化，可以忽略此邮件。'),
    "tl": ('I-reset ang iyong BloomPrint password',
           'Gamitin ang link sa ibaba para pumili ng bagong password. Isang beses itong gumagana at mag-e-expire sa loob ng 24 na oras. Kung hindi ikaw ang humiling nito, walang nagbago at pwede mong balewalain ang mensaheng ito.'),
}

EVENTS["password_changed"] = {
    "en": ('Your BloomPrint password was changed',
           "The password on your account has been changed and every other device has been signed out. If this wasn't you, write to us straight away."),
    "es": ('Se ha cambiado tu contraseña de BloomPrint',
           'La contraseña de tu cuenta se ha cambiado y se ha cerrado la sesión en los demás dispositivos. Si no has sido tú, escríbenos de inmediato.'),
    "fr": ('Votre mot de passe BloomPrint a été modifié',
           "Le mot de passe de votre compte a été modifié et tous les autres appareils ont été déconnectés. Si ce n'était pas vous, écrivez-nous immédiatement."),
    "pt": ('A sua palavra-passe do BloomPrint foi alterada',
           'A palavra-passe da sua conta foi alterada e a sessão foi terminada em todos os outros dispositivos. Se não foi você, escreva-nos de imediato.'),
    "it": ('La tua password BloomPrint è stata modificata',
           'La password del tuo account è stata modificata e tutti gli altri dispositivi sono stati disconnessi. Se non sei stato tu, scrivici subito.'),
    "de": ('Dein BloomPrint-Passwort wurde geändert',
           'Das Passwort deines Kontos wurde geändert und alle anderen Geräte wurden abgemeldet. Wenn du das nicht warst, schreib uns sofort.'),
    "nl": ('Je BloomPrint-wachtwoord is gewijzigd',
           'Het wachtwoord van je account is gewijzigd en alle andere apparaten zijn afgemeld. Was jij dit niet, mail ons dan meteen.'),
    "sv": ('Ditt BloomPrint-lösenord har ändrats',
           'Lösenordet för ditt konto har ändrats och alla andra enheter har loggats ut. Om det inte var du, hör av dig direkt.'),
    "pl": ('Hasło do BloomPrint zostało zmienione',
           'Hasło do Twojego konta zostało zmienione, a pozostałe urządzenia zostały wylogowane. Jeśli to nie Ty, napisz do nas natychmiast.'),
    "ru": ('Пароль BloomPrint изменён',
           'Пароль вашей учётной записи изменён, на всех других устройствах выполнен выход. Если это были не вы, напишите нам немедленно.'),
    "uk": ('Пароль BloomPrint змінено',
           'Пароль вашого облікового запису змінено, на всіх інших пристроях виконано вихід. Якщо це були не ви, напишіть нам негайно.'),
    "sr": ('Ваша BloomPrint лозинка је промењена',
           'Лозинка вашег налога је промењена и одјављени сте са свих других уређаја. Ако то нисте били ви, пишите нам одмах.'),
    "hr": ('Vaša BloomPrint lozinka je promijenjena',
           'Lozinka vašeg računa je promijenjena i odjavljeni ste sa svih drugih uređaja. Ako to niste bili vi, pišite nam odmah.'),
    "tr": ('BloomPrint şifreniz değiştirildi',
           'Hesabınızın şifresi değiştirildi ve diğer tüm cihazlardaki oturumlar kapatıldı. Bunu siz yapmadıysanız hemen bize yazın.'),
    "ro": ('Parola ta BloomPrint a fost schimbată',
           'Parola contului tău a fost schimbată și toate celelalte dispozitive au fost deconectate. Dacă nu ai fost tu, scrie-ne imediat.'),
    "el": ('Ο κωδικός σας στο BloomPrint άλλαξε',
           'Ο κωδικός του λογαριασμού σας άλλαξε και έγινε αποσύνδεση από κάθε άλλη συσκευή. Αν δεν το κάνατε εσείς, γράψτε μας αμέσως.'),
    "lt": ('Jūsų BloomPrint slaptažodis pakeistas',
           'Jūsų paskyros slaptažodis pakeistas, o visi kiti įrenginiai atjungti. Jei tai buvote ne jūs, parašykite mums nedelsdami.'),
    "ar": ('تم تغيير كلمة مرور BloomPrint',
           'تم تغيير كلمة مرور حسابك وتسجيل الخروج من جميع الأجهزة الأخرى. إذا لم تكن أنت، فراسلنا فورًا.'),
    "he": ('הסיסמה שלך ב-BloomPrint שונתה',
           'הסיסמה לחשבון שלך שונתה וכל שאר המכשירים נותקו. אם זה לא היה אתם, כתבו לנו מיד.'),
    "hi": ('आपका BloomPrint पासवर्ड बदल दिया गया',
           'आपके खाते का पासवर्ड बदल दिया गया है और बाकी सभी डिवाइस से साइन आउट कर दिया गया है। यदि यह आपने नहीं किया, तो हमें तुरंत लिखें।'),
    "ka": ('თქვენი BloomPrint-ის პაროლი შეიცვალა',
           'თქვენი ანგარიშის პაროლი შეიცვალა და ყველა სხვა მოწყობილობიდან სისტემიდან გამოხვედით. თუ ეს თქვენ არ იყავით, მოგვწერეთ დაუყოვნებლივ.'),
    "ja": ('BloomPrint のパスワードが変更されました',
           'アカウントのパスワードが変更され、他のすべての端末からサインアウトされました。心当たりがない場合はすぐにご連絡ください。'),
    "ko": ('BloomPrint 비밀번호가 변경되었습니다',
           '계정 비밀번호가 변경되었고 다른 모든 기기에서 로그아웃되었습니다. 본인이 아니라면 즉시 연락해 주세요.'),
    "zh": ('你的 BloomPrint 密码已更改',
           '你的账户密码已更改，其他所有设备均已退出登录。如果这不是你操作的，请立即联系我们。'),
    "tl": ('Nabago ang iyong BloomPrint password',
           'Nabago ang password ng iyong account at na-sign out na ang lahat ng ibang device. Kung hindi ikaw ang gumawa nito, sulatan mo kami agad.'),
}